// What the kit says, in the 21 languages of the app (Plan §84). English is the source. Data only:
// the build writes each key once in the bundle (README, "Texts"). Numbers and dates are never
// written here: they go through Intl in the user's language.

export const KIT_TEXTS = {
  en: {
    matches: "Matches",
    newMatch: "New match",
    noMatches: "No matches yet",
    needsChat: "Open “{game}” from a conversation to play with someone.",
    started: "Started {date}",
    delete: "Delete",
    confirmDelete: "Delete this match? It is gone from this phone for good.",
    cancel: "Cancel",
    back: "Back to the matches",
    you: "You",
    them: "Opponent",
    yourTurn: "Your turn",
    theirTurn: "Their turn",
    waiting: "Waiting for the other person to open “{game}” in this conversation",
    howToInvite: "The other person has to open this game too. Tap 📨 above to invite them.",
    connecting: "Reaching the other phone…",
    tossing: "Tossing a coin to see who starts…",
    youStart: "The coin says you start",
    theyStart: "The coin says they start",
    pending: "Your move has not reached the other phone yet. It goes when you both have “{game}” open.",
    notOpen: "The other person does not have “{game}” open in this conversation.",
    unreachable: "The other phone cannot be reached right now.",
    retry: "Try again",
    left: "The other person left the match.",
    update: "The other phone has “{game}” {version}, newer than yours. Update it to keep playing together.",
    busy: "The other person is in another match. They have been asked to join this one.",
    denied: "This match is not on the other phone: it may be with someone else, or it was deleted there.",
    invited: "The other person started a new match.",
    elsewhere: "The other person is playing another of your matches.",
    join: "Join",
    open: "Open",
    dismiss: "Not now",
    fork: "Your two phones disagree about this match. Which one goes on?",
    forkMine: "Mine",
    forkTheirs: "Theirs",
    badMove: "The other phone sent a move that breaks the rules. It was not applied.",
    full: "No room left on this phone to save the match.",
    invalid: "The coin toss did not check out: this match is not valid.",
    abandonedThem: "The other person did not reveal the coin in time: this match was abandoned.",
    abandonedYou: "This phone did not reveal the coin in time: this match was abandoned.",
    tooLong: "This series is too long to go on. Start a new match.",
    resign: "Resign",
    confirmResign: "Resign this round? The other person wins it.",
    youWon: "You won",
    youLost: "You lost",
    draw: "Draw",
    theyResigned: "The other person resigned",
    youResigned: "You resigned",
    again: "Play again",
    sendResult: "Send the result to the chat",
    score: "Score",
    round: "Round {n}",
    over: "Round over",
    ended: "Match over",
    sayIWon: "I won",
    sayYouWon: "you won",
    sayDraw: "a draw",
    sayDraws: "draws: {n}",
    say: "{game}: {result}, {score}",
    error: "Something went wrong. Try again.",
  },
  es: {
    matches: "Partidas",
    newMatch: "Nueva partida",
    noMatches: "Todavía no hay partidas",
    needsChat: "Abre «{game}» desde una conversación para jugar con alguien.",
    started: "Empezada el {date}",
    delete: "Borrar",
    confirmDelete: "¿Borrar esta partida? Desaparece de este teléfono para siempre.",
    cancel: "Cancelar",
    back: "Volver a las partidas",
    you: "Tú",
    them: "Rival",
    yourTurn: "Te toca",
    theirTurn: "Le toca al rival",
    waiting: "Esperando a que la otra persona abra «{game}» en esta conversación",
    howToInvite: "La otra persona también tiene que abrir este juego. Toca 📨 arriba para invitarla.",
    connecting: "Conectando con el otro teléfono…",
    tossing: "Lanzando una moneda para ver quién empieza…",
    youStart: "La moneda dice que empiezas tú",
    theyStart: "La moneda dice que empieza el rival",
    pending: "Tu jugada aún no ha llegado al otro teléfono. Saldrá cuando los dos tengáis «{game}» abierto.",
    notOpen: "La otra persona no tiene «{game}» abierto en esta conversación.",
    unreachable: "Ahora mismo no se puede llegar al otro teléfono.",
    retry: "Reintentar",
    left: "La otra persona ha salido de la partida.",
    update: "El otro teléfono tiene «{game}» {version}, más nuevo que el tuyo. Actualízalo para seguir jugando juntos.",
    busy: "La otra persona está en otra partida. Le hemos pedido que se una a esta.",
    denied: "Esta partida no está en el otro teléfono: puede que sea con otra persona o que la borraran allí.",
    invited: "La otra persona ha empezado una partida nueva.",
    elsewhere: "La otra persona está jugando otra de vuestras partidas.",
    join: "Unirse",
    open: "Abrir",
    dismiss: "Ahora no",
    fork: "Vuestros dos teléfonos no coinciden en esta partida. ¿Cuál sigue?",
    forkMine: "La mía",
    forkTheirs: "La suya",
    badMove: "El otro teléfono envió una jugada que rompe las reglas. No se ha aplicado.",
    full: "No queda sitio en este teléfono para guardar la partida.",
    invalid: "El sorteo con la moneda no cuadra: esta partida no es válida.",
    abandonedThem: "La otra persona no reveló la moneda a tiempo: la partida queda abandonada.",
    abandonedYou: "Este teléfono no reveló la moneda a tiempo: la partida queda abandonada.",
    tooLong: "Esta serie es demasiado larga para seguir. Empieza una partida nueva.",
    resign: "Rendirse",
    confirmResign: "¿Rendirte en esta ronda? La gana el rival.",
    youWon: "Has ganado",
    youLost: "Has perdido",
    draw: "Empate",
    theyResigned: "La otra persona se ha rendido",
    youResigned: "Te has rendido",
    again: "Jugar otra",
    sendResult: "Enviar el resultado al chat",
    score: "Marcador",
    round: "Ronda {n}",
    over: "Ronda terminada",
    ended: "Partida terminada",
    sayIWon: "gané yo",
    sayYouWon: "ganaste tú",
    sayDraw: "empate",
    sayDraws: "empates: {n}",
    say: "{game}: {result}, {score}",
    error: "Algo ha fallado. Inténtalo otra vez.",
  },
  fr: {
    matches: "Parties",
    newMatch: "Nouvelle partie",
    noMatches: "Aucune partie pour l’instant",
    needsChat: "Ouvrez « {game} » depuis une conversation pour jouer avec quelqu’un.",
    started: "Commencée le {date}",
    delete: "Supprimer",
    confirmDelete: "Supprimer cette partie ? Elle disparaît de ce téléphone pour de bon.",
    cancel: "Annuler",
    back: "Retour aux parties",
    you: "Vous",
    them: "Adversaire",
    yourTurn: "À vous de jouer",
    theirTurn: "Au tour de l’adversaire",
    waiting: "En attente que l’autre personne ouvre « {game} » dans cette conversation",
    howToInvite: "L’autre personne doit aussi ouvrir ce jeu. Touchez 📨 ci-dessus pour l’inviter.",
    connecting: "Connexion à l’autre téléphone…",
    tossing: "Pile ou face pour savoir qui commence…",
    youStart: "La pièce dit que vous commencez",
    theyStart: "La pièce dit que l’adversaire commence",
    pending: "Votre coup n’est pas encore arrivé sur l’autre téléphone. Il partira quand vous aurez tous les deux « {game} » ouvert.",
    notOpen: "L’autre personne n’a pas « {game} » ouvert dans cette conversation.",
    unreachable: "L’autre téléphone est injoignable pour le moment.",
    retry: "Réessayer",
    left: "L’autre personne a quitté la partie.",
    update: "L’autre téléphone a « {game} » {version}, plus récent que le vôtre. Mettez-le à jour pour continuer à jouer ensemble.",
    busy: "L’autre personne est dans une autre partie. On lui a demandé de rejoindre celle-ci.",
    denied: "Cette partie n’est pas sur l’autre téléphone : elle est peut-être avec quelqu’un d’autre, ou elle y a été supprimée.",
    invited: "L’autre personne a commencé une nouvelle partie.",
    elsewhere: "L’autre personne joue une autre de vos parties.",
    join: "Rejoindre",
    open: "Ouvrir",
    dismiss: "Pas maintenant",
    fork: "Vos deux téléphones ne sont pas d’accord sur cette partie. Laquelle continue ?",
    forkMine: "La mienne",
    forkTheirs: "La sienne",
    badMove: "L’autre téléphone a envoyé un coup contraire aux règles. Il n’a pas été appliqué.",
    full: "Plus de place sur ce téléphone pour enregistrer la partie.",
    invalid: "Le tirage à pile ou face ne correspond pas : cette partie n’est pas valable.",
    abandonedThem: "L’autre personne n’a pas révélé la pièce à temps : la partie est abandonnée.",
    abandonedYou: "Ce téléphone n’a pas révélé la pièce à temps : la partie est abandonnée.",
    tooLong: "Cette série est trop longue pour continuer. Commencez une nouvelle partie.",
    resign: "Abandonner",
    confirmResign: "Abandonner cette manche ? L’adversaire la gagne.",
    youWon: "Vous avez gagné",
    youLost: "Vous avez perdu",
    draw: "Match nul",
    theyResigned: "L’autre personne a abandonné",
    youResigned: "Vous avez abandonné",
    again: "Rejouer",
    sendResult: "Envoyer le résultat dans la conversation",
    score: "Score",
    round: "Manche {n}",
    over: "Manche terminée",
    ended: "Partie terminée",
    sayIWon: "j’ai gagné",
    sayYouWon: "tu as gagné",
    sayDraw: "match nul",
    sayDraws: "nuls : {n}",
    say: "{game} : {result}, {score}",
    error: "Un problème est survenu. Réessayez.",
  },
  de: {
    matches: "Partien",
    newMatch: "Neue Partie",
    noMatches: "Noch keine Partien",
    needsChat: "Öffne „{game}“ in einem Chat, um mit jemandem zu spielen.",
    started: "Begonnen am {date}",
    delete: "Löschen",
    confirmDelete: "Diese Partie löschen? Sie ist dann für immer von diesem Telefon weg.",
    cancel: "Abbrechen",
    back: "Zurück zu den Partien",
    you: "Du",
    them: "Gegenüber",
    yourTurn: "Du bist dran",
    theirTurn: "Dein Gegenüber ist dran",
    waiting: "Warte, bis die andere Person „{game}“ in diesem Chat öffnet",
    howToInvite: "Die andere Person muss dieses Spiel auch öffnen. Tippe oben auf 📨, um sie einzuladen.",
    connecting: "Verbinde mit dem anderen Telefon …",
    tossing: "Eine Münze entscheidet, wer anfängt …",
    youStart: "Die Münze sagt: Du fängst an",
    theyStart: "Die Münze sagt: Dein Gegenüber fängt an",
    pending: "Dein Zug ist noch nicht auf dem anderen Telefon angekommen. Er geht raus, sobald ihr beide „{game}“ geöffnet habt.",
    notOpen: "Die andere Person hat „{game}“ in diesem Chat nicht geöffnet.",
    unreachable: "Das andere Telefon ist gerade nicht erreichbar.",
    retry: "Erneut versuchen",
    left: "Die andere Person hat die Partie verlassen.",
    update: "Das andere Telefon hat „{game}“ {version}, neuer als deins. Aktualisiere es, um weiter zusammen zu spielen.",
    busy: "Die andere Person ist in einer anderen Partie. Sie wurde gebeten, dieser beizutreten.",
    denied: "Diese Partie ist nicht auf dem anderen Telefon: Vielleicht ist sie mit jemand anderem, oder sie wurde dort gelöscht.",
    invited: "Die andere Person hat eine neue Partie begonnen.",
    elsewhere: "Die andere Person spielt gerade eine andere eurer Partien.",
    join: "Beitreten",
    open: "Öffnen",
    dismiss: "Nicht jetzt",
    fork: "Eure beiden Telefone sind sich bei dieser Partie nicht einig. Welche geht weiter?",
    forkMine: "Meine",
    forkTheirs: "Die andere",
    badMove: "Das andere Telefon hat einen regelwidrigen Zug geschickt. Er wurde nicht übernommen.",
    full: "Kein Platz mehr auf diesem Telefon, um die Partie zu speichern.",
    invalid: "Der Münzwurf stimmt nicht: Diese Partie ist ungültig.",
    abandonedThem: "Die andere Person hat die Münze nicht rechtzeitig aufgedeckt: Die Partie ist abgebrochen.",
    abandonedYou: "Dieses Telefon hat die Münze nicht rechtzeitig aufgedeckt: Die Partie ist abgebrochen.",
    tooLong: "Diese Serie ist zu lang, um weiterzugehen. Starte eine neue Partie.",
    resign: "Aufgeben",
    confirmResign: "Diese Runde aufgeben? Dein Gegenüber gewinnt sie.",
    youWon: "Du hast gewonnen",
    youLost: "Du hast verloren",
    draw: "Unentschieden",
    theyResigned: "Die andere Person hat aufgegeben",
    youResigned: "Du hast aufgegeben",
    again: "Noch mal",
    sendResult: "Ergebnis in den Chat schicken",
    score: "Spielstand",
    round: "Runde {n}",
    over: "Runde vorbei",
    ended: "Partie beendet",
    sayIWon: "ich habe gewonnen",
    sayYouWon: "du hast gewonnen",
    sayDraw: "unentschieden",
    sayDraws: "Unentschieden: {n}",
    say: "{game}: {result}, {score}",
    error: "Etwas ist schiefgelaufen. Versuch es noch mal.",
  },
  it: {
    matches: "Partite",
    newMatch: "Nuova partita",
    noMatches: "Ancora nessuna partita",
    needsChat: "Apri «{game}» da una conversazione per giocare con qualcuno.",
    started: "Iniziata il {date}",
    delete: "Elimina",
    confirmDelete: "Eliminare questa partita? Sparisce da questo telefono per sempre.",
    cancel: "Annulla",
    back: "Torna alle partite",
    you: "Tu",
    them: "Avversario",
    yourTurn: "Tocca a te",
    theirTurn: "Tocca all’avversario",
    waiting: "In attesa che l’altra persona apra «{game}» in questa conversazione",
    howToInvite: "Anche l’altra persona deve aprire questo gioco. Tocca 📨 qui sopra per invitarla.",
    connecting: "Collegamento con l’altro telefono…",
    tossing: "Testa o croce per decidere chi inizia…",
    youStart: "La moneta dice che inizi tu",
    theyStart: "La moneta dice che inizia l’avversario",
    pending: "La tua mossa non è ancora arrivata all’altro telefono. Partirà quando avrete entrambi «{game}» aperto.",
    notOpen: "L’altra persona non ha «{game}» aperto in questa conversazione.",
    unreachable: "L’altro telefono non è raggiungibile in questo momento.",
    retry: "Riprova",
    left: "L’altra persona ha lasciato la partita.",
    update: "L’altro telefono ha «{game}» {version}, più recente del tuo. Aggiornalo per continuare a giocare insieme.",
    busy: "L’altra persona è in un’altra partita. Le è stato chiesto di unirsi a questa.",
    denied: "Questa partita non è sull’altro telefono: forse è con qualcun altro, o è stata eliminata lì.",
    invited: "L’altra persona ha iniziato una nuova partita.",
    elsewhere: "L’altra persona sta giocando un’altra delle vostre partite.",
    join: "Unisciti",
    open: "Apri",
    dismiss: "Non ora",
    fork: "I vostri due telefoni non sono d’accordo su questa partita. Quale continua?",
    forkMine: "La mia",
    forkTheirs: "La sua",
    badMove: "L’altro telefono ha inviato una mossa contro le regole. Non è stata applicata.",
    full: "Non c’è più spazio su questo telefono per salvare la partita.",
    invalid: "Il lancio della moneta non torna: questa partita non è valida.",
    abandonedThem: "L’altra persona non ha rivelato la moneta in tempo: la partita è stata abbandonata.",
    abandonedYou: "Questo telefono non ha rivelato la moneta in tempo: la partita è stata abbandonata.",
    tooLong: "Questa serie è troppo lunga per continuare. Inizia una nuova partita.",
    resign: "Abbandona",
    confirmResign: "Abbandonare questo round? Lo vince l’avversario.",
    youWon: "Hai vinto",
    youLost: "Hai perso",
    draw: "Pareggio",
    theyResigned: "L’altra persona ha abbandonato",
    youResigned: "Hai abbandonato",
    again: "Gioca ancora",
    sendResult: "Invia il risultato in chat",
    score: "Punteggio",
    round: "Round {n}",
    over: "Round finito",
    ended: "Partita finita",
    sayIWon: "ho vinto io",
    sayYouWon: "hai vinto tu",
    sayDraw: "pareggio",
    sayDraws: "pareggi: {n}",
    say: "{game}: {result}, {score}",
    error: "Qualcosa è andato storto. Riprova.",
  },
  pt: {
    matches: "Partidas",
    newMatch: "Nova partida",
    noMatches: "Nenhuma partida ainda",
    needsChat: "Abra “{game}” em uma conversa para jogar com alguém.",
    started: "Iniciada em {date}",
    delete: "Apagar",
    confirmDelete: "Apagar esta partida? Ela some deste telefone para sempre.",
    cancel: "Cancelar",
    back: "Voltar às partidas",
    you: "Você",
    them: "Adversário",
    yourTurn: "Sua vez",
    theirTurn: "Vez do adversário",
    waiting: "Esperando a outra pessoa abrir “{game}” nesta conversa",
    howToInvite: "A outra pessoa também precisa abrir este jogo. Toque em 📨 acima para convidá-la.",
    connecting: "Conectando ao outro telefone…",
    tossing: "Jogando uma moeda para ver quem começa…",
    youStart: "A moeda diz que você começa",
    theyStart: "A moeda diz que o adversário começa",
    pending: "Sua jogada ainda não chegou ao outro telefone. Ela vai quando vocês dois estiverem com “{game}” aberto.",
    notOpen: "A outra pessoa não está com “{game}” aberto nesta conversa.",
    unreachable: "Não é possível alcançar o outro telefone agora.",
    retry: "Tentar de novo",
    left: "A outra pessoa saiu da partida.",
    update: "O outro telefone tem “{game}” {version}, mais novo que o seu. Atualize para continuarem jogando juntos.",
    busy: "A outra pessoa está em outra partida. Pedimos que ela entre nesta.",
    denied: "Esta partida não está no outro telefone: talvez seja com outra pessoa, ou foi apagada lá.",
    invited: "A outra pessoa começou uma nova partida.",
    elsewhere: "A outra pessoa está jogando outra partida de vocês.",
    join: "Entrar",
    open: "Abrir",
    dismiss: "Agora não",
    fork: "Os dois telefones não concordam sobre esta partida. Qual continua?",
    forkMine: "A minha",
    forkTheirs: "A outra",
    badMove: "O outro telefone enviou uma jogada que quebra as regras. Ela não foi aplicada.",
    full: "Não há mais espaço neste telefone para salvar a partida.",
    invalid: "O sorteio com a moeda não confere: esta partida não é válida.",
    abandonedThem: "A outra pessoa não revelou a moeda a tempo: a partida foi abandonada.",
    abandonedYou: "Este telefone não revelou a moeda a tempo: a partida foi abandonada.",
    tooLong: "Esta série está longa demais para continuar. Comece uma nova partida.",
    resign: "Desistir",
    confirmResign: "Desistir desta rodada? O adversário vence.",
    youWon: "Você venceu",
    youLost: "Você perdeu",
    draw: "Empate",
    theyResigned: "A outra pessoa desistiu",
    youResigned: "Você desistiu",
    again: "Jogar de novo",
    sendResult: "Enviar o resultado para a conversa",
    score: "Placar",
    round: "Rodada {n}",
    over: "Rodada encerrada",
    ended: "Partida encerrada",
    sayIWon: "eu ganhei",
    sayYouWon: "você ganhou",
    sayDraw: "empate",
    sayDraws: "empates: {n}",
    say: "{game}: {result}, {score}",
    error: "Algo deu errado. Tente de novo.",
  },
  ro: {
    matches: "Partide",
    newMatch: "Partidă nouă",
    noMatches: "Nicio partidă încă",
    needsChat: "Deschide „{game}” dintr-o conversație ca să joci cu cineva.",
    started: "Începută pe {date}",
    delete: "Șterge",
    confirmDelete: "Ștergi această partidă? Dispare definitiv de pe acest telefon.",
    cancel: "Anulează",
    back: "Înapoi la partide",
    you: "Tu",
    them: "Adversar",
    yourTurn: "E rândul tău",
    theirTurn: "E rândul adversarului",
    waiting: "Se așteaptă ca cealaltă persoană să deschidă „{game}” în această conversație",
    howToInvite: "Și cealaltă persoană trebuie să deschidă acest joc. Atinge 📨 de mai sus ca s-o inviți.",
    connecting: "Se contactează celălalt telefon…",
    tossing: "Se aruncă o monedă ca să vedem cine începe…",
    youStart: "Moneda spune că începi tu",
    theyStart: "Moneda spune că începe adversarul",
    pending: "Mutarea ta n-a ajuns încă pe celălalt telefon. Pleacă atunci când aveți amândoi „{game}” deschis.",
    notOpen: "Cealaltă persoană nu are „{game}” deschis în această conversație.",
    unreachable: "Celălalt telefon nu poate fi contactat acum.",
    retry: "Încearcă din nou",
    left: "Cealaltă persoană a ieșit din partidă.",
    update: "Celălalt telefon are „{game}” {version}, mai nou decât al tău. Actualizează-l ca să jucați în continuare împreună.",
    busy: "Cealaltă persoană e într-o altă partidă. A fost rugată să intre în aceasta.",
    denied: "Această partidă nu e pe celălalt telefon: poate e cu altcineva sau a fost ștearsă acolo.",
    invited: "Cealaltă persoană a început o partidă nouă.",
    elsewhere: "Cealaltă persoană joacă o altă partidă de-a voastră.",
    join: "Intră",
    open: "Deschide",
    dismiss: "Nu acum",
    fork: "Cele două telefoane nu se înțeleg asupra acestei partide. Care continuă?",
    forkMine: "A mea",
    forkTheirs: "Cealaltă",
    badMove: "Celălalt telefon a trimis o mutare care încalcă regulile. Nu a fost aplicată.",
    full: "Nu mai e loc pe acest telefon pentru a salva partida.",
    invalid: "Aruncarea monedei nu se verifică: această partidă nu e validă.",
    abandonedThem: "Cealaltă persoană nu a dezvăluit moneda la timp: partida a fost abandonată.",
    abandonedYou: "Acest telefon nu a dezvăluit moneda la timp: partida a fost abandonată.",
    tooLong: "Seria asta e prea lungă ca să continue. Începe o partidă nouă.",
    resign: "Abandonează",
    confirmResign: "Abandonezi această rundă? O câștigă adversarul.",
    youWon: "Ai câștigat",
    youLost: "Ai pierdut",
    draw: "Egalitate",
    theyResigned: "Cealaltă persoană a abandonat",
    youResigned: "Ai abandonat",
    again: "Încă o dată",
    sendResult: "Trimite rezultatul în conversație",
    score: "Scor",
    round: "Runda {n}",
    over: "Rundă terminată",
    ended: "Partidă terminată",
    sayIWon: "am câștigat eu",
    sayYouWon: "ai câștigat tu",
    sayDraw: "egalitate",
    sayDraws: "egalități: {n}",
    say: "{game}: {result}, {score}",
    error: "Ceva n-a mers. Încearcă din nou.",
  },
  pl: {
    matches: "Partie",
    newMatch: "Nowa partia",
    noMatches: "Jeszcze nie ma partii",
    needsChat: "Otwórz „{game}” z rozmowy, aby zagrać z kimś.",
    started: "Rozpoczęta {date}",
    delete: "Usuń",
    confirmDelete: "Usunąć tę partię? Zniknie z tego telefonu na zawsze.",
    cancel: "Anuluj",
    back: "Wróć do partii",
    you: "Ty",
    them: "Przeciwnik",
    yourTurn: "Twój ruch",
    theirTurn: "Ruch przeciwnika",
    waiting: "Czekamy, aż druga osoba otworzy „{game}” w tej rozmowie",
    howToInvite: "Druga osoba też musi otworzyć tę grę. Dotknij 📨 powyżej, aby ją zaprosić.",
    connecting: "Łączenie z drugim telefonem…",
    tossing: "Rzut monetą: kto zaczyna…",
    youStart: "Moneta mówi, że zaczynasz ty",
    theyStart: "Moneta mówi, że zaczyna przeciwnik",
    pending: "Twój ruch jeszcze nie dotarł do drugiego telefonu. Wyjdzie, gdy oboje otworzycie „{game}”.",
    notOpen: "Druga osoba nie ma otwartej gry „{game}” w tej rozmowie.",
    unreachable: "Drugi telefon jest teraz nieosiągalny.",
    retry: "Spróbuj ponownie",
    left: "Druga osoba opuściła partię.",
    update: "Drugi telefon ma „{game}” {version}, nowszą niż twoja. Zaktualizuj, aby dalej grać razem.",
    busy: "Druga osoba jest w innej partii. Poprosiliśmy ją, by dołączyła do tej.",
    denied: "Tej partii nie ma na drugim telefonie: może jest z kimś innym albo została tam usunięta.",
    invited: "Druga osoba zaczęła nową partię.",
    elsewhere: "Druga osoba gra w inną waszą partię.",
    join: "Dołącz",
    open: "Otwórz",
    dismiss: "Nie teraz",
    fork: "Wasze telefony nie zgadzają się co do tej partii. Która gra dalej?",
    forkMine: "Moja",
    forkTheirs: "Druga",
    badMove: "Drugi telefon przysłał ruch niezgodny z zasadami. Nie został zastosowany.",
    full: "Brak miejsca na tym telefonie, by zapisać partię.",
    invalid: "Rzut monetą się nie zgadza: ta partia jest nieważna.",
    abandonedThem: "Druga osoba nie odkryła monety na czas: partię porzucono.",
    abandonedYou: "Ten telefon nie odkrył monety na czas: partię porzucono.",
    tooLong: "Ta seria jest za długa, by grać dalej. Zacznij nową partię.",
    resign: "Poddaj się",
    confirmResign: "Poddać tę rundę? Wygrywa ją przeciwnik.",
    youWon: "Wygrywasz",
    youLost: "Przegrywasz",
    draw: "Remis",
    theyResigned: "Druga osoba się poddała",
    youResigned: "Poddajesz rundę",
    again: "Zagraj jeszcze raz",
    sendResult: "Wyślij wynik do rozmowy",
    score: "Wynik",
    round: "Runda {n}",
    over: "Runda zakończona",
    ended: "Partia zakończona",
    sayIWon: "moja wygrana",
    sayYouWon: "twoja wygrana",
    sayDraw: "remis",
    sayDraws: "remisy: {n}",
    say: "{game}: {result}, {score}",
    error: "Coś poszło nie tak. Spróbuj ponownie.",
  },
  ru: {
    matches: "Партии",
    newMatch: "Новая партия",
    noMatches: "Партий пока нет",
    needsChat: "Откройте «{game}» из чата, чтобы играть с кем-то.",
    started: "Начата {date}",
    delete: "Удалить",
    confirmDelete: "Удалить эту партию? Она исчезнет с этого телефона навсегда.",
    cancel: "Отмена",
    back: "К партиям",
    you: "Вы",
    them: "Соперник",
    yourTurn: "Ваш ход",
    theirTurn: "Ход соперника",
    waiting: "Ждём, когда собеседник откроет «{game}» в этом чате",
    howToInvite: "Собеседнику тоже нужно открыть эту игру. Нажмите 📨 вверху, чтобы пригласить его.",
    connecting: "Связываемся с другим телефоном…",
    tossing: "Бросаем монетку, чтобы решить, кто начинает…",
    youStart: "Монетка говорит: начинаете вы",
    theyStart: "Монетка говорит: начинает соперник",
    pending: "Ваш ход ещё не дошёл до другого телефона. Он уйдёт, когда вы оба откроете «{game}».",
    notOpen: "Собеседник не открыл «{game}» в этом чате.",
    unreachable: "Сейчас не удаётся связаться с другим телефоном.",
    retry: "Повторить",
    left: "Собеседник вышел из партии.",
    update: "На другом телефоне версия «{game}» {version} новее вашей. Обновите, чтобы и дальше играть вместе.",
    busy: "Собеседник в другой партии. Его попросили присоединиться к этой.",
    denied: "Этой партии нет на другом телефоне: возможно, она с кем-то другим или там её удалили.",
    invited: "Собеседник начал новую партию.",
    elsewhere: "Собеседник играет в другую вашу партию.",
    join: "Присоединиться",
    open: "Открыть",
    dismiss: "Не сейчас",
    fork: "Ваши телефоны расходятся в этой партии. Какую продолжить?",
    forkMine: "Мою",
    forkTheirs: "Другую",
    badMove: "Другой телефон прислал ход против правил. Он не применён.",
    full: "На этом телефоне не осталось места, чтобы сохранить партию.",
    invalid: "Бросок монетки не сходится: партия недействительна.",
    abandonedThem: "Собеседник не открыл монетку вовремя: партия прервана.",
    abandonedYou: "Этот телефон не открыл монетку вовремя: партия прервана.",
    tooLong: "Эта серия слишком длинная, чтобы продолжать. Начните новую партию.",
    resign: "Сдаться",
    confirmResign: "Сдать этот раунд? Его выиграет соперник.",
    youWon: "Вы выиграли",
    youLost: "Вы проиграли",
    draw: "Ничья",
    theyResigned: "Собеседник сдался",
    youResigned: "Вы сдались",
    again: "Ещё раз",
    sendResult: "Отправить результат в чат",
    score: "Счёт",
    round: "Раунд {n}",
    over: "Раунд окончен",
    ended: "Партия окончена",
    sayIWon: "победа за мной",
    sayYouWon: "победа за тобой",
    sayDraw: "ничья",
    sayDraws: "ничьих: {n}",
    say: "{game}: {result}, {score}",
    error: "Что-то пошло не так. Попробуйте ещё раз.",
  },
  uk: {
    matches: "Партії",
    newMatch: "Нова партія",
    noMatches: "Партій ще немає",
    needsChat: "Відкрийте «{game}» з чату, щоб грати з кимось.",
    started: "Почато {date}",
    delete: "Видалити",
    confirmDelete: "Видалити цю партію? Вона зникне з цього телефона назавжди.",
    cancel: "Скасувати",
    back: "До партій",
    you: "Ви",
    them: "Суперник",
    yourTurn: "Ваш хід",
    theirTurn: "Хід суперника",
    waiting: "Чекаємо, поки співрозмовник відкриє «{game}» у цьому чаті",
    howToInvite: "Співрозмовнику теж треба відкрити цю гру. Натисніть 📨 угорі, щоб запросити його.",
    connecting: "Зв’язуємося з іншим телефоном…",
    tossing: "Підкидаємо монетку, щоб вирішити, хто починає…",
    youStart: "Монетка каже: починаєте ви",
    theyStart: "Монетка каже: починає суперник",
    pending: "Ваш хід ще не дійшов до іншого телефона. Він піде, коли ви обоє відкриєте «{game}».",
    notOpen: "Співрозмовник не відкрив «{game}» у цьому чаті.",
    unreachable: "Зараз не вдається зв’язатися з іншим телефоном.",
    retry: "Спробувати ще",
    left: "Співрозмовник вийшов із партії.",
    update: "На іншому телефоні версія «{game}» {version} новіша за вашу. Оновіть, щоб і далі грати разом.",
    busy: "Співрозмовник в іншій партії. Його попросили приєднатися до цієї.",
    denied: "Цієї партії немає на іншому телефоні: можливо, вона з кимось іншим або її там видалили.",
    invited: "Співрозмовник почав нову партію.",
    elsewhere: "Співрозмовник грає в іншу вашу партію.",
    join: "Приєднатися",
    open: "Відкрити",
    dismiss: "Не зараз",
    fork: "Ваші телефони розходяться щодо цієї партії. Яку продовжити?",
    forkMine: "Мою",
    forkTheirs: "Іншу",
    badMove: "Інший телефон надіслав хід усупереч правилам. Його не застосовано.",
    full: "На цьому телефоні не лишилося місця, щоб зберегти партію.",
    invalid: "Підкидання монетки не сходиться: партія недійсна.",
    abandonedThem: "Співрозмовник не відкрив монетку вчасно: партію перервано.",
    abandonedYou: "Цей телефон не відкрив монетку вчасно: партію перервано.",
    tooLong: "Ця серія задовга, щоб продовжувати. Почніть нову партію.",
    resign: "Здатися",
    confirmResign: "Здати цей раунд? Його виграє суперник.",
    youWon: "Ви виграли",
    youLost: "Ви програли",
    draw: "Нічия",
    theyResigned: "Співрозмовник здався",
    youResigned: "Ви здалися",
    again: "Ще раз",
    sendResult: "Надіслати результат у чат",
    score: "Рахунок",
    round: "Раунд {n}",
    over: "Раунд завершено",
    ended: "Партію завершено",
    sayIWon: "перемога за мною",
    sayYouWon: "перемога за тобою",
    sayDraw: "нічия",
    sayDraws: "нічиїх: {n}",
    say: "{game}: {result}, {score}",
    error: "Щось пішло не так. Спробуйте ще раз.",
  },
  tr: {
    matches: "Maçlar",
    newMatch: "Yeni maç",
    noMatches: "Henüz maç yok",
    needsChat: "Biriyle oynamak için “{game}” oyununu bir sohbetten açın.",
    started: "Başlangıç: {date}",
    delete: "Sil",
    confirmDelete: "Bu maç silinsin mi? Bu telefondan kalıcı olarak gider.",
    cancel: "İptal",
    back: "Maçlara dön",
    you: "Siz",
    them: "Rakip",
    yourTurn: "Sıra sizde",
    theirTurn: "Sıra rakipte",
    waiting: "Karşı tarafın bu sohbette “{game}” oyununu açması bekleniyor",
    howToInvite: "Karşı tarafın da bu oyunu açması gerekiyor. Davet etmek için yukarıdaki 📨 simgesine dokunun.",
    connecting: "Diğer telefona ulaşılıyor…",
    tossing: "Kimin başlayacağı için yazı tura atılıyor…",
    youStart: "Yazı tura: siz başlıyorsunuz",
    theyStart: "Yazı tura: rakip başlıyor",
    pending: "Hamleniz henüz diğer telefona ulaşmadı. İkiniz de “{game}” oyununu açtığınızda gidecek.",
    notOpen: "Karşı taraf bu sohbette “{game}” oyununu açmamış.",
    unreachable: "Diğer telefona şu anda ulaşılamıyor.",
    retry: "Tekrar dene",
    left: "Karşı taraf maçtan ayrıldı.",
    update: "Diğer telefonda “{game}” {version} var, sizinkinden yeni. Birlikte oynamaya devam etmek için güncelleyin.",
    busy: "Karşı taraf başka bir maçta. Bu maça katılması istendi.",
    denied: "Bu maç diğer telefonda yok: başka biriyle olabilir ya da orada silinmiş olabilir.",
    invited: "Karşı taraf yeni bir maç başlattı.",
    elsewhere: "Karşı taraf başka bir maçınızı oynuyor.",
    join: "Katıl",
    open: "Aç",
    dismiss: "Şimdi değil",
    fork: "İki telefon bu maçta anlaşamıyor. Hangisi devam etsin?",
    forkMine: "Benimki",
    forkTheirs: "Onunki",
    badMove: "Diğer telefon kurallara aykırı bir hamle gönderdi. Uygulanmadı.",
    full: "Bu telefonda maçı kaydedecek yer kalmadı.",
    invalid: "Yazı tura doğrulanamadı: bu maç geçersiz.",
    abandonedThem: "Karşı taraf yazı turayı zamanında açıklamadı: maç terk edildi.",
    abandonedYou: "Bu telefon yazı turayı zamanında açıklamadı: maç terk edildi.",
    tooLong: "Bu seri devam edemeyecek kadar uzun. Yeni bir maç başlatın.",
    resign: "Pes et",
    confirmResign: "Bu turda pes edilsin mi? Turu rakip kazanır.",
    youWon: "Kazandınız",
    youLost: "Kaybettiniz",
    draw: "Berabere",
    theyResigned: "Karşı taraf pes etti",
    youResigned: "Pes ettiniz",
    again: "Tekrar oyna",
    sendResult: "Sonucu sohbete gönder",
    score: "Skor",
    round: "{n}. tur",
    over: "Tur bitti",
    ended: "Maç bitti",
    sayIWon: "ben kazandım",
    sayYouWon: "sen kazandın",
    sayDraw: "berabere",
    sayDraws: "beraberlik: {n}",
    say: "{game}: {result}, {score}",
    error: "Bir sorun oluştu. Tekrar deneyin.",
  },
  ar: {
    matches: "المباريات",
    newMatch: "مباراة جديدة",
    noMatches: "لا توجد مباريات بعد",
    needsChat: "افتح «{game}» من محادثة لتلعب مع أحد.",
    started: "بدأت في {date}",
    delete: "حذف",
    confirmDelete: "هل تحذف هذه المباراة؟ ستختفي من هذا الهاتف نهائيًا.",
    cancel: "إلغاء",
    back: "العودة إلى المباريات",
    you: "أنت",
    them: "المنافس",
    yourTurn: "دورك",
    theirTurn: "دور المنافس",
    waiting: "بانتظار أن يفتح الطرف الآخر «{game}» في هذه المحادثة",
    howToInvite: "يجب أن يفتح الطرف الآخر هذه اللعبة أيضًا. اضغط 📨 في الأعلى لدعوته.",
    connecting: "جارٍ الوصول إلى الهاتف الآخر…",
    tossing: "رمي عملة لمعرفة من يبدأ…",
    youStart: "العملة تقول إنك تبدأ",
    theyStart: "العملة تقول إن المنافس يبدأ",
    pending: "لم تصل حركتك إلى الهاتف الآخر بعد. ستُرسل عندما يكون «{game}» مفتوحًا لدى كليكما.",
    notOpen: "ليس لدى الطرف الآخر «{game}» مفتوحًا في هذه المحادثة.",
    unreachable: "لا يمكن الوصول إلى الهاتف الآخر الآن.",
    retry: "إعادة المحاولة",
    left: "غادر الطرف الآخر المباراة.",
    update: "لدى الهاتف الآخر «{game}» {version}، وهو أحدث من نسختك. حدّثه لتواصلا اللعب معًا.",
    busy: "الطرف الآخر في مباراة أخرى. طُلب منه الانضمام إلى هذه.",
    denied: "هذه المباراة ليست على الهاتف الآخر: ربما هي مع شخص آخر، أو حُذفت هناك.",
    invited: "بدأ الطرف الآخر مباراة جديدة.",
    elsewhere: "الطرف الآخر يلعب مباراة أخرى من مبارياتكما.",
    join: "انضمام",
    open: "فتح",
    dismiss: "ليس الآن",
    fork: "هاتفاكما مختلفان بشأن هذه المباراة. أيّهما يستمر؟",
    forkMine: "نسختي",
    forkTheirs: "نسخة الطرف الآخر",
    badMove: "أرسل الهاتف الآخر حركة تخالف القواعد. لم تُطبَّق.",
    full: "لا توجد مساحة كافية على هذا الهاتف لحفظ المباراة.",
    invalid: "رمي العملة لا يتطابق: هذه المباراة غير صالحة.",
    abandonedThem: "لم يكشف الطرف الآخر العملة في الوقت المناسب: تُركت المباراة.",
    abandonedYou: "لم يكشف هذا الهاتف العملة في الوقت المناسب: تُركت المباراة.",
    tooLong: "هذه السلسلة أطول من أن تستمر. ابدأ مباراة جديدة.",
    resign: "استسلام",
    confirmResign: "هل تستسلم في هذه الجولة؟ سيفوز بها المنافس.",
    youWon: "فزت",
    youLost: "خسرت",
    draw: "تعادل",
    theyResigned: "استسلم الطرف الآخر",
    youResigned: "استسلمت",
    again: "العب مرة أخرى",
    sendResult: "إرسال النتيجة إلى المحادثة",
    score: "النتيجة",
    round: "الجولة {n}",
    over: "انتهت الجولة",
    ended: "انتهت المباراة",
    sayIWon: "الفوز لي",
    sayYouWon: "الفوز لك",
    sayDraw: "تعادل",
    sayDraws: "التعادلات: {n}",
    say: "{game}: {result}، {score}",
    error: "حدث خطأ ما. حاول مرة أخرى.",
  },
  hi: {
    matches: "मैच",
    newMatch: "नया मैच",
    noMatches: "अभी कोई मैच नहीं",
    needsChat: "किसी के साथ खेलने के लिए “{game}” को किसी बातचीत से खोलें।",
    started: "{date} को शुरू हुआ",
    delete: "हटाएँ",
    confirmDelete: "यह मैच हटाएँ? यह इस फ़ोन से हमेशा के लिए चला जाएगा।",
    cancel: "रद्द करें",
    back: "मैचों पर वापस",
    you: "आप",
    them: "प्रतिद्वंद्वी",
    yourTurn: "आपकी बारी",
    theirTurn: "प्रतिद्वंद्वी की बारी",
    waiting: "दूसरे व्यक्ति के इस बातचीत में “{game}” खोलने का इंतज़ार",
    howToInvite: "दूसरे व्यक्ति को भी यह गेम खोलना होगा। उन्हें बुलाने के लिए ऊपर 📨 पर टैप करें।",
    connecting: "दूसरे फ़ोन से जुड़ रहे हैं…",
    tossing: "कौन शुरू करेगा, यह तय करने के लिए सिक्का उछाला जा रहा है…",
    youStart: "सिक्के के अनुसार आप शुरू करेंगे",
    theyStart: "सिक्के के अनुसार प्रतिद्वंद्वी शुरू करेंगे",
    pending: "आपकी चाल अभी दूसरे फ़ोन तक नहीं पहुँची। जब आप दोनों “{game}” खोलेंगे, तब यह जाएगी।",
    notOpen: "दूसरे व्यक्ति ने इस बातचीत में “{game}” नहीं खोला है।",
    unreachable: "अभी दूसरे फ़ोन तक नहीं पहुँचा जा सकता।",
    retry: "फिर से कोशिश करें",
    left: "दूसरे व्यक्ति ने मैच छोड़ दिया।",
    update: "दूसरे फ़ोन पर “{game}” {version} है, जो आपसे नया है। साथ खेलते रहने के लिए इसे अपडेट करें।",
    busy: "दूसरे व्यक्ति किसी और मैच में हैं। उनसे इस मैच में आने को कहा गया है।",
    denied: "यह मैच दूसरे फ़ोन पर नहीं है: शायद यह किसी और के साथ है, या वहाँ हटा दिया गया।",
    invited: "दूसरे व्यक्ति ने नया मैच शुरू किया।",
    elsewhere: "दूसरे व्यक्ति आपका कोई और मैच खेल रहे हैं।",
    join: "शामिल हों",
    open: "खोलें",
    dismiss: "अभी नहीं",
    fork: "आपके दोनों फ़ोन इस मैच पर सहमत नहीं हैं। कौन-सा आगे चले?",
    forkMine: "मेरा",
    forkTheirs: "दूसरा",
    badMove: "दूसरे फ़ोन ने नियम तोड़ने वाली चाल भेजी। उसे लागू नहीं किया गया।",
    full: "मैच सहेजने के लिए इस फ़ोन में जगह नहीं बची।",
    invalid: "सिक्के का उछाल मेल नहीं खाता: यह मैच मान्य नहीं है।",
    abandonedThem: "दूसरे व्यक्ति ने समय पर सिक्का नहीं दिखाया: मैच छोड़ दिया गया।",
    abandonedYou: "इस फ़ोन ने समय पर सिक्का नहीं दिखाया: मैच छोड़ दिया गया।",
    tooLong: "यह सीरीज़ आगे चलने के लिए बहुत लंबी है। नया मैच शुरू करें।",
    resign: "हार मानें",
    confirmResign: "इस राउंड में हार मानें? यह प्रतिद्वंद्वी जीतेंगे।",
    youWon: "आप जीत गए",
    youLost: "आप हार गए",
    draw: "बराबरी",
    theyResigned: "दूसरे व्यक्ति ने हार मान ली",
    youResigned: "आपने हार मान ली",
    again: "फिर से खेलें",
    sendResult: "नतीजा बातचीत में भेजें",
    score: "स्कोर",
    round: "राउंड {n}",
    over: "राउंड खत्म",
    ended: "मैच खत्म",
    sayIWon: "मेरी जीत",
    sayYouWon: "तुम्हारी जीत",
    sayDraw: "बराबरी",
    sayDraws: "बराबरी: {n}",
    say: "{game}: {result}, {score}",
    error: "कुछ गड़बड़ हो गई। फिर से कोशिश करें।",
  },
  bn: {
    matches: "ম্যাচ",
    newMatch: "নতুন ম্যাচ",
    noMatches: "এখনও কোনো ম্যাচ নেই",
    needsChat: "কারও সঙ্গে খেলতে কোনো কথোপকথন থেকে “{game}” খুলুন।",
    started: "শুরু {date}",
    delete: "মুছুন",
    confirmDelete: "এই ম্যাচটি মুছবেন? এটি এই ফোন থেকে চিরতরে চলে যাবে।",
    cancel: "বাতিল",
    back: "ম্যাচে ফিরে যান",
    you: "আপনি",
    them: "প্রতিপক্ষ",
    yourTurn: "আপনার পালা",
    theirTurn: "প্রতিপক্ষের পালা",
    waiting: "অন্যজন এই কথোপকথনে “{game}” খোলার অপেক্ষায়",
    howToInvite: "অন্যজনকেও এই গেমটি খুলতে হবে। তাঁকে আমন্ত্রণ জানাতে ওপরের 📨 ট্যাপ করুন।",
    connecting: "অন্য ফোনের সঙ্গে যোগাযোগ করা হচ্ছে…",
    tossing: "কে শুরু করবে তা ঠিক করতে কয়েন টস হচ্ছে…",
    youStart: "কয়েন বলছে আপনি শুরু করবেন",
    theyStart: "কয়েন বলছে প্রতিপক্ষ শুরু করবেন",
    pending: "আপনার চাল এখনও অন্য ফোনে পৌঁছায়নি। আপনারা দুজনেই “{game}” খুললে এটি যাবে।",
    notOpen: "অন্যজন এই কথোপকথনে “{game}” খোলেননি।",
    unreachable: "এই মুহূর্তে অন্য ফোনে পৌঁছানো যাচ্ছে না।",
    retry: "আবার চেষ্টা করুন",
    left: "অন্যজন ম্যাচ ছেড়ে গেছেন।",
    update: "অন্য ফোনে “{game}” {version} আছে, যা আপনারটির চেয়ে নতুন। একসঙ্গে খেলা চালিয়ে যেতে এটি আপডেট করুন।",
    busy: "অন্যজন অন্য একটি ম্যাচে আছেন। তাঁকে এই ম্যাচে যোগ দিতে বলা হয়েছে।",
    denied: "এই ম্যাচটি অন্য ফোনে নেই: হয়তো এটি অন্য কারও সঙ্গে, বা সেখানে মুছে ফেলা হয়েছে।",
    invited: "অন্যজন একটি নতুন ম্যাচ শুরু করেছেন।",
    elsewhere: "অন্যজন আপনাদের আরেকটি ম্যাচ খেলছেন।",
    join: "যোগ দিন",
    open: "খুলুন",
    dismiss: "এখন নয়",
    fork: "আপনাদের দুটি ফোন এই ম্যাচ নিয়ে একমত নয়। কোনটি চলবে?",
    forkMine: "আমারটি",
    forkTheirs: "অন্যটি",
    badMove: "অন্য ফোন নিয়ম ভাঙা একটি চাল পাঠিয়েছে। এটি প্রয়োগ করা হয়নি।",
    full: "ম্যাচ সংরক্ষণের জন্য এই ফোনে আর জায়গা নেই।",
    invalid: "কয়েন টস মেলেনি: এই ম্যাচ বৈধ নয়।",
    abandonedThem: "অন্যজন সময়মতো কয়েন প্রকাশ করেননি: ম্যাচটি পরিত্যক্ত হয়েছে।",
    abandonedYou: "এই ফোন সময়মতো কয়েন প্রকাশ করেনি: ম্যাচটি পরিত্যক্ত হয়েছে।",
    tooLong: "এই সিরিজ চালিয়ে যাওয়ার জন্য খুব লম্বা। নতুন ম্যাচ শুরু করুন।",
    resign: "হার মানুন",
    confirmResign: "এই রাউন্ডে হার মানবেন? এটি প্রতিপক্ষ জিতবেন।",
    youWon: "আপনি জিতেছেন",
    youLost: "আপনি হেরেছেন",
    draw: "ড্র",
    theyResigned: "অন্যজন হার মেনেছেন",
    youResigned: "আপনি হার মেনেছেন",
    again: "আবার খেলুন",
    sendResult: "ফলাফল কথোপকথনে পাঠান",
    score: "স্কোর",
    round: "রাউন্ড {n}",
    over: "রাউন্ড শেষ",
    ended: "ম্যাচ শেষ",
    sayIWon: "আমি জিতেছি",
    sayYouWon: "তুমি জিতেছ",
    sayDraw: "ড্র",
    sayDraws: "ড্র: {n}",
    say: "{game}: {result}, {score}",
    error: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
  },
  id: {
    matches: "Pertandingan",
    newMatch: "Pertandingan baru",
    noMatches: "Belum ada pertandingan",
    needsChat: "Buka “{game}” dari percakapan untuk bermain dengan seseorang.",
    started: "Dimulai {date}",
    delete: "Hapus",
    confirmDelete: "Hapus pertandingan ini? Pertandingan akan hilang dari ponsel ini selamanya.",
    cancel: "Batal",
    back: "Kembali ke pertandingan",
    you: "Anda",
    them: "Lawan",
    yourTurn: "Giliran Anda",
    theirTurn: "Giliran lawan",
    waiting: "Menunggu orang lain membuka “{game}” di percakapan ini",
    howToInvite: "Orang lain juga harus membuka game ini. Ketuk 📨 di atas untuk mengundangnya.",
    connecting: "Menghubungi ponsel lain…",
    tossing: "Melempar koin untuk menentukan siapa yang mulai…",
    youStart: "Koin memilih Anda yang mulai",
    theyStart: "Koin memilih lawan yang mulai",
    pending: "Langkah Anda belum sampai ke ponsel lain. Langkah ini dikirim saat Anda berdua membuka “{game}”.",
    notOpen: "Orang lain belum membuka “{game}” di percakapan ini.",
    unreachable: "Ponsel lain tidak dapat dihubungi saat ini.",
    retry: "Coba lagi",
    left: "Orang lain keluar dari pertandingan.",
    update: "Ponsel lain memiliki “{game}” {version}, lebih baru dari milik Anda. Perbarui agar bisa terus bermain bersama.",
    busy: "Orang lain sedang di pertandingan lain. Mereka sudah diminta bergabung ke pertandingan ini.",
    denied: "Pertandingan ini tidak ada di ponsel lain: mungkin dengan orang lain, atau sudah dihapus di sana.",
    invited: "Orang lain memulai pertandingan baru.",
    elsewhere: "Orang lain sedang memainkan pertandingan Anda yang lain.",
    join: "Gabung",
    open: "Buka",
    dismiss: "Nanti saja",
    fork: "Kedua ponsel tidak sepakat soal pertandingan ini. Mana yang dilanjutkan?",
    forkMine: "Milik saya",
    forkTheirs: "Milik lawan",
    badMove: "Ponsel lain mengirim langkah yang melanggar aturan. Langkah itu tidak diterapkan.",
    full: "Tidak ada ruang tersisa di ponsel ini untuk menyimpan pertandingan.",
    invalid: "Lemparan koin tidak cocok: pertandingan ini tidak sah.",
    abandonedThem: "Orang lain tidak membuka koin tepat waktu: pertandingan ditinggalkan.",
    abandonedYou: "Ponsel ini tidak membuka koin tepat waktu: pertandingan ditinggalkan.",
    tooLong: "Rangkaian ini terlalu panjang untuk dilanjutkan. Mulai pertandingan baru.",
    resign: "Menyerah",
    confirmResign: "Menyerah di ronde ini? Lawan yang menang.",
    youWon: "Anda menang",
    youLost: "Anda kalah",
    draw: "Seri",
    theyResigned: "Orang lain menyerah",
    youResigned: "Anda menyerah",
    again: "Main lagi",
    sendResult: "Kirim hasil ke percakapan",
    score: "Skor",
    round: "Ronde {n}",
    over: "Ronde selesai",
    ended: "Pertandingan selesai",
    sayIWon: "aku menang",
    sayYouWon: "kamu menang",
    sayDraw: "seri",
    sayDraws: "seri: {n}",
    say: "{game}: {result}, {score}",
    error: "Terjadi kesalahan. Coba lagi.",
  },
  vi: {
    matches: "Ván đấu",
    newMatch: "Ván mới",
    noMatches: "Chưa có ván nào",
    needsChat: "Mở “{game}” từ một cuộc trò chuyện để chơi với ai đó.",
    started: "Bắt đầu {date}",
    delete: "Xóa",
    confirmDelete: "Xóa ván này? Ván sẽ biến mất khỏi điện thoại này vĩnh viễn.",
    cancel: "Hủy",
    back: "Quay lại danh sách ván",
    you: "Bạn",
    them: "Đối thủ",
    yourTurn: "Đến lượt bạn",
    theirTurn: "Đến lượt đối thủ",
    waiting: "Đang chờ người kia mở “{game}” trong cuộc trò chuyện này",
    howToInvite: "Người kia cũng cần mở trò chơi này. Chạm 📨 ở trên để mời họ.",
    connecting: "Đang kết nối với điện thoại kia…",
    tossing: "Đang tung đồng xu để xem ai đi trước…",
    youStart: "Đồng xu chọn bạn đi trước",
    theyStart: "Đồng xu chọn đối thủ đi trước",
    pending: "Nước đi của bạn chưa đến điện thoại kia. Nó sẽ được gửi khi cả hai cùng mở “{game}”.",
    notOpen: "Người kia chưa mở “{game}” trong cuộc trò chuyện này.",
    unreachable: "Hiện không liên lạc được với điện thoại kia.",
    retry: "Thử lại",
    left: "Người kia đã rời ván.",
    update: "Điện thoại kia có “{game}” {version}, mới hơn của bạn. Hãy cập nhật để tiếp tục chơi cùng nhau.",
    busy: "Người kia đang ở ván khác. Họ đã được mời vào ván này.",
    denied: "Ván này không có trên điện thoại kia: có thể là với người khác, hoặc đã bị xóa ở đó.",
    invited: "Người kia vừa bắt đầu một ván mới.",
    elsewhere: "Người kia đang chơi một ván khác của hai bạn.",
    join: "Tham gia",
    open: "Mở",
    dismiss: "Để sau",
    fork: "Hai điện thoại không thống nhất về ván này. Tiếp tục bản nào?",
    forkMine: "Của tôi",
    forkTheirs: "Của người kia",
    badMove: "Điện thoại kia gửi một nước đi trái luật. Nước đi đó không được áp dụng.",
    full: "Điện thoại này hết chỗ để lưu ván.",
    invalid: "Kết quả tung đồng xu không khớp: ván này không hợp lệ.",
    abandonedThem: "Người kia không công bố đồng xu kịp lúc: ván đã bị bỏ dở.",
    abandonedYou: "Điện thoại này không công bố đồng xu kịp lúc: ván đã bị bỏ dở.",
    tooLong: "Chuỗi ván này quá dài để tiếp tục. Hãy bắt đầu ván mới.",
    resign: "Đầu hàng",
    confirmResign: "Đầu hàng ở hiệp này? Đối thủ sẽ thắng hiệp.",
    youWon: "Bạn thắng",
    youLost: "Bạn thua",
    draw: "Hòa",
    theyResigned: "Người kia đã đầu hàng",
    youResigned: "Bạn đã đầu hàng",
    again: "Chơi lại",
    sendResult: "Gửi kết quả vào cuộc trò chuyện",
    score: "Tỉ số",
    round: "Hiệp {n}",
    over: "Hết hiệp",
    ended: "Ván đã kết thúc",
    sayIWon: "mình thắng",
    sayYouWon: "bạn thắng",
    sayDraw: "hòa",
    sayDraws: "hòa: {n}",
    say: "{game}: {result}, {score}",
    error: "Đã có lỗi. Hãy thử lại.",
  },
  th: {
    matches: "การแข่งขัน",
    newMatch: "การแข่งขันใหม่",
    noMatches: "ยังไม่มีการแข่งขัน",
    needsChat: "เปิด “{game}” จากแชทเพื่อเล่นกับใครสักคน",
    started: "เริ่มเมื่อ {date}",
    delete: "ลบ",
    confirmDelete: "ลบการแข่งขันนี้ไหม จะหายไปจากโทรศัพท์เครื่องนี้ถาวร",
    cancel: "ยกเลิก",
    back: "กลับไปที่การแข่งขัน",
    you: "คุณ",
    them: "คู่แข่ง",
    yourTurn: "ตาของคุณ",
    theirTurn: "ตาของคู่แข่ง",
    waiting: "กำลังรออีกฝ่ายเปิด “{game}” ในแชทนี้",
    howToInvite: "อีกฝ่ายต้องเปิดเกมนี้ด้วย แตะ 📨 ด้านบนเพื่อชวน",
    connecting: "กำลังติดต่อโทรศัพท์อีกเครื่อง…",
    tossing: "กำลังโยนเหรียญเพื่อดูว่าใครเริ่มก่อน…",
    youStart: "เหรียญบอกว่าคุณเริ่มก่อน",
    theyStart: "เหรียญบอกว่าคู่แข่งเริ่มก่อน",
    pending: "ตาเดินของคุณยังไปไม่ถึงโทรศัพท์อีกเครื่อง จะส่งไปเมื่อทั้งสองฝ่ายเปิด “{game}”",
    notOpen: "อีกฝ่ายไม่ได้เปิด “{game}” ในแชทนี้",
    unreachable: "ตอนนี้ติดต่อโทรศัพท์อีกเครื่องไม่ได้",
    retry: "ลองอีกครั้ง",
    left: "อีกฝ่ายออกจากการแข่งขันแล้ว",
    update: "โทรศัพท์อีกเครื่องมี “{game}” {version} ซึ่งใหม่กว่าของคุณ อัปเดตเพื่อเล่นด้วยกันต่อ",
    busy: "อีกฝ่ายอยู่ในการแข่งขันอื่น ได้ขอให้เข้าร่วมการแข่งขันนี้แล้ว",
    denied: "การแข่งขันนี้ไม่มีในโทรศัพท์อีกเครื่อง อาจเป็นการแข่งกับคนอื่น หรือถูกลบที่นั่นแล้ว",
    invited: "อีกฝ่ายเริ่มการแข่งขันใหม่",
    elsewhere: "อีกฝ่ายกำลังเล่นการแข่งขันอื่นของคุณทั้งคู่",
    join: "เข้าร่วม",
    open: "เปิด",
    dismiss: "ไว้ทีหลัง",
    fork: "โทรศัพท์ทั้งสองเครื่องเห็นไม่ตรงกันเรื่องการแข่งขันนี้ จะเล่นต่อแบบไหน",
    forkMine: "ของฉัน",
    forkTheirs: "ของอีกฝ่าย",
    badMove: "โทรศัพท์อีกเครื่องส่งตาเดินที่ผิดกติกามา จึงไม่ได้นำมาใช้",
    full: "โทรศัพท์เครื่องนี้ไม่มีพื้นที่เหลือสำหรับบันทึกการแข่งขัน",
    invalid: "ผลการโยนเหรียญไม่ตรงกัน การแข่งขันนี้ไม่ถูกต้อง",
    abandonedThem: "อีกฝ่ายไม่ได้เปิดผลเหรียญทันเวลา การแข่งขันถูกละทิ้ง",
    abandonedYou: "โทรศัพท์เครื่องนี้ไม่ได้เปิดผลเหรียญทันเวลา การแข่งขันถูกละทิ้ง",
    tooLong: "ซีรีส์นี้ยาวเกินกว่าจะเล่นต่อ เริ่มการแข่งขันใหม่",
    resign: "ยอมแพ้",
    confirmResign: "ยอมแพ้ในรอบนี้ไหม คู่แข่งจะชนะรอบนี้",
    youWon: "คุณชนะ",
    youLost: "คุณแพ้",
    draw: "เสมอ",
    theyResigned: "อีกฝ่ายยอมแพ้",
    youResigned: "คุณยอมแพ้",
    again: "เล่นอีกครั้ง",
    sendResult: "ส่งผลไปที่แชท",
    score: "คะแนน",
    round: "รอบที่ {n}",
    over: "จบรอบ",
    ended: "จบการแข่งขัน",
    sayIWon: "ฉันชนะ",
    sayYouWon: "เธอชนะ",
    sayDraw: "เสมอ",
    sayDraws: "เสมอ: {n}",
    say: "{game}: {result} {score}",
    error: "เกิดข้อผิดพลาด ลองอีกครั้ง",
  },
  ja: {
    matches: "対局",
    newMatch: "新しい対局",
    noMatches: "まだ対局はありません",
    needsChat: "誰かと遊ぶには、チャットから「{game}」を開いてください。",
    started: "{date}に開始",
    delete: "削除",
    confirmDelete: "この対局を削除しますか？この端末から完全に消えます。",
    cancel: "キャンセル",
    back: "対局一覧に戻る",
    you: "あなた",
    them: "相手",
    yourTurn: "あなたの番",
    theirTurn: "相手の番",
    waiting: "相手がこのチャットで「{game}」を開くのを待っています",
    howToInvite: "相手もこのゲームを開く必要があります。招待するには上の 📨 をタップしてください。",
    connecting: "相手の端末に接続しています…",
    tossing: "コイントスで先手を決めています…",
    youStart: "コイントスの結果、あなたが先手です",
    theyStart: "コイントスの結果、相手が先手です",
    pending: "あなたの手はまだ相手の端末に届いていません。二人とも「{game}」を開くと送られます。",
    notOpen: "相手はこのチャットで「{game}」を開いていません。",
    unreachable: "今は相手の端末に接続できません。",
    retry: "再試行",
    left: "相手が対局を抜けました。",
    update: "相手の端末の「{game}」は{version}で、あなたのより新しいバージョンです。一緒に遊び続けるには更新してください。",
    busy: "相手は別の対局中です。この対局に参加するよう伝えました。",
    denied: "この対局は相手の端末にありません。別の人との対局か、相手側で削除された可能性があります。",
    invited: "相手が新しい対局を始めました。",
    elsewhere: "相手はあなたたちの別の対局をプレイ中です。",
    join: "参加",
    open: "開く",
    dismiss: "あとで",
    fork: "二台の端末でこの対局の内容が食い違っています。どちらを続けますか？",
    forkMine: "自分の",
    forkTheirs: "相手の",
    badMove: "相手の端末からルール違反の手が届きました。適用していません。",
    full: "この端末に対局を保存する空き容量がありません。",
    invalid: "コイントスの検証に失敗しました。この対局は無効です。",
    abandonedThem: "相手がコイントスの結果を時間内に公開しませんでした。対局は中止されました。",
    abandonedYou: "この端末がコイントスの結果を時間内に公開しませんでした。対局は中止されました。",
    tooLong: "このシリーズは長すぎて続けられません。新しい対局を始めてください。",
    resign: "投了",
    confirmResign: "このラウンドを投了しますか？相手の勝ちになります。",
    youWon: "あなたの勝ち",
    youLost: "あなたの負け",
    draw: "引き分け",
    theyResigned: "相手が投了しました",
    youResigned: "投了しました",
    again: "もう一度",
    sendResult: "結果をチャットに送る",
    score: "スコア",
    round: "第{n}ラウンド",
    over: "ラウンド終了",
    ended: "対局終了",
    sayIWon: "私の勝ち",
    sayYouWon: "あなたの勝ち",
    sayDraw: "引き分け",
    sayDraws: "引き分け：{n}",
    say: "{game}：{result}、{score}",
    error: "問題が発生しました。もう一度お試しください。",
  },
  ko: {
    matches: "경기",
    newMatch: "새 경기",
    noMatches: "아직 경기가 없습니다",
    needsChat: "누군가와 하려면 대화에서 “{game}”을(를) 여세요.",
    started: "{date} 시작",
    delete: "삭제",
    confirmDelete: "이 경기를 삭제할까요? 이 휴대폰에서 영구히 사라집니다.",
    cancel: "취소",
    back: "경기 목록으로",
    you: "나",
    them: "상대",
    yourTurn: "내 차례",
    theirTurn: "상대 차례",
    waiting: "상대가 이 대화에서 “{game}”을(를) 열기를 기다리는 중",
    howToInvite: "상대도 이 게임을 열어야 합니다. 초대하려면 위의 📨을 누르세요.",
    connecting: "상대 휴대폰에 연결하는 중…",
    tossing: "누가 먼저 할지 동전을 던지는 중…",
    youStart: "동전 결과: 내가 먼저",
    theyStart: "동전 결과: 상대가 먼저",
    pending: "내 수가 아직 상대 휴대폰에 닿지 않았습니다. 두 사람 모두 “{game}”을(를) 열면 전송됩니다.",
    notOpen: "상대가 이 대화에서 “{game}”을(를) 열지 않았습니다.",
    unreachable: "지금은 상대 휴대폰에 연결할 수 없습니다.",
    retry: "다시 시도",
    left: "상대가 경기에서 나갔습니다.",
    update: "상대 휴대폰의 “{game}”은(는) {version}(으)로 내 것보다 새 버전입니다. 계속 함께 하려면 업데이트하세요.",
    busy: "상대가 다른 경기 중입니다. 이 경기에 참여해 달라고 요청했습니다.",
    denied: "이 경기는 상대 휴대폰에 없습니다. 다른 사람과의 경기이거나 그쪽에서 삭제되었을 수 있습니다.",
    invited: "상대가 새 경기를 시작했습니다.",
    elsewhere: "상대가 두 사람의 다른 경기를 하고 있습니다.",
    join: "참여",
    open: "열기",
    dismiss: "나중에",
    fork: "두 휴대폰의 경기 내용이 다릅니다. 어느 쪽으로 계속할까요?",
    forkMine: "내 것",
    forkTheirs: "상대 것",
    badMove: "상대 휴대폰이 규칙에 어긋나는 수를 보냈습니다. 적용하지 않았습니다.",
    full: "이 휴대폰에 경기를 저장할 공간이 없습니다.",
    invalid: "동전 던지기 결과가 맞지 않습니다. 이 경기는 무효입니다.",
    abandonedThem: "상대가 제때 동전 결과를 공개하지 않았습니다. 경기가 중단되었습니다.",
    abandonedYou: "이 휴대폰이 제때 동전 결과를 공개하지 않았습니다. 경기가 중단되었습니다.",
    tooLong: "이 시리즈는 너무 길어서 계속할 수 없습니다. 새 경기를 시작하세요.",
    resign: "기권",
    confirmResign: "이번 라운드를 기권할까요? 상대가 이깁니다.",
    youWon: "이겼습니다",
    youLost: "졌습니다",
    draw: "무승부",
    theyResigned: "상대가 기권했습니다",
    youResigned: "기권했습니다",
    again: "한 번 더",
    sendResult: "결과를 대화에 보내기",
    score: "점수",
    round: "{n}라운드",
    over: "라운드 종료",
    ended: "경기 종료",
    sayIWon: "내가 이겼어",
    sayYouWon: "네가 이겼어",
    sayDraw: "무승부",
    sayDraws: "무승부: {n}",
    say: "{game}: {result}, {score}",
    error: "문제가 발생했습니다. 다시 시도하세요.",
  },
  "zh-CN": {
    matches: "对局",
    newMatch: "新对局",
    noMatches: "还没有对局",
    needsChat: "从聊天中打开“{game}”，即可与人对战。",
    started: "开始于 {date}",
    delete: "删除",
    confirmDelete: "删除此对局？它将从这部手机上永久消失。",
    cancel: "取消",
    back: "返回对局列表",
    you: "你",
    them: "对手",
    yourTurn: "轮到你了",
    theirTurn: "轮到对手",
    waiting: "正在等待对方在此聊天中打开“{game}”",
    howToInvite: "对方也需要打开这个游戏。点上方的 📨 邀请对方。",
    connecting: "正在连接对方的手机…",
    tossing: "正在掷硬币决定谁先手…",
    youStart: "硬币结果：你先手",
    theyStart: "硬币结果：对手先手",
    pending: "你的这一步还没送达对方手机。等你们都打开“{game}”时会发出。",
    notOpen: "对方没有在此聊天中打开“{game}”。",
    unreachable: "现在无法连接对方的手机。",
    retry: "重试",
    left: "对方已离开对局。",
    update: "对方手机上的“{game}”是 {version}，比你的新。请更新以继续一起玩。",
    busy: "对方正在另一局中。已请对方加入这一局。",
    denied: "对方手机上没有这一局：可能是和别人下的，或已在那边删除。",
    invited: "对方开了一个新对局。",
    elsewhere: "对方正在玩你们的另一局。",
    join: "加入",
    open: "打开",
    dismiss: "以后再说",
    fork: "两部手机对这一局的记录不一致。继续哪一个？",
    forkMine: "我的",
    forkTheirs: "对方的",
    badMove: "对方手机发来了违反规则的一步，未予采用。",
    full: "这部手机没有空间保存对局了。",
    invalid: "掷硬币结果核对不上：此对局无效。",
    abandonedThem: "对方没有及时公开硬币结果：对局已放弃。",
    abandonedYou: "这部手机没有及时公开硬币结果：对局已放弃。",
    tooLong: "这个系列太长，无法继续。请开始新对局。",
    resign: "认输",
    confirmResign: "在本轮认输？对手将赢得本轮。",
    youWon: "你赢了",
    youLost: "你输了",
    draw: "平局",
    theyResigned: "对方认输了",
    youResigned: "你认输了",
    again: "再来一局",
    sendResult: "把结果发到聊天",
    score: "比分",
    round: "第 {n} 轮",
    over: "本轮结束",
    ended: "对局结束",
    sayIWon: "我赢了",
    sayYouWon: "你赢了",
    sayDraw: "平局",
    sayDraws: "平局：{n}",
    say: "{game}：{result}，{score}",
    error: "出了点问题，请重试。",
  },
  "zh-TW": {
    matches: "對局",
    newMatch: "新對局",
    noMatches: "還沒有對局",
    needsChat: "從聊天中開啟「{game}」，就能和別人對戰。",
    started: "開始於 {date}",
    delete: "刪除",
    confirmDelete: "刪除這個對局？它會從這支手機上永久消失。",
    cancel: "取消",
    back: "返回對局列表",
    you: "你",
    them: "對手",
    yourTurn: "輪到你了",
    theirTurn: "輪到對手",
    waiting: "正在等對方在這個聊天中開啟「{game}」",
    howToInvite: "對方也需要開啟這個遊戲。點上方的 📨 邀請對方。",
    connecting: "正在連線到對方的手機…",
    tossing: "正在擲硬幣決定誰先…",
    youStart: "硬幣結果：你先",
    theyStart: "硬幣結果：對手先",
    pending: "你這一步還沒送到對方手機。等你們都開啟「{game}」時就會送出。",
    notOpen: "對方沒有在這個聊天中開啟「{game}」。",
    unreachable: "現在無法連到對方的手機。",
    retry: "重試",
    left: "對方已離開對局。",
    update: "對方手機上的「{game}」是 {version}，比你的新。請更新以繼續一起玩。",
    busy: "對方正在另一局中。已請對方加入這一局。",
    denied: "對方手機上沒有這一局：可能是和別人下的，或已在那邊刪除。",
    invited: "對方開了一個新對局。",
    elsewhere: "對方正在玩你們的另一局。",
    join: "加入",
    open: "開啟",
    dismiss: "稍後再說",
    fork: "兩支手機對這一局的紀錄不一致。要繼續哪一個？",
    forkMine: "我的",
    forkTheirs: "對方的",
    badMove: "對方手機傳來違反規則的一步，未予採用。",
    full: "這支手機沒有空間儲存對局了。",
    invalid: "擲硬幣的結果核對不符：這個對局無效。",
    abandonedThem: "對方沒有及時公開硬幣結果：對局已放棄。",
    abandonedYou: "這支手機沒有及時公開硬幣結果：對局已放棄。",
    tooLong: "這個系列太長，無法繼續。請開始新對局。",
    resign: "認輸",
    confirmResign: "在這一輪認輸？對手將贏得這一輪。",
    youWon: "你贏了",
    youLost: "你輸了",
    draw: "平手",
    theyResigned: "對方認輸了",
    youResigned: "你認輸了",
    again: "再來一局",
    sendResult: "把結果傳到聊天",
    score: "比數",
    round: "第 {n} 輪",
    over: "這一輪結束",
    ended: "對局結束",
    sayIWon: "我贏了",
    sayYouWon: "你贏了",
    sayDraw: "平手",
    sayDraws: "平手：{n}",
    say: "{game}：{result}，{score}",
    error: "發生問題，請重試。",
  },
};
