// What chess adds to the kit's texts, in the 21 languages of the app: its name, the board for a
// screen reader, the two colours, how a game ends, the promotion dialog (cm-chessboard's own speaks
// only English and German) and the result for the chat. English is the source. Data only
// (README, "Texts").
export const TEXTS = {
  en: {
    name: "Chess",
    board: "Chessboard",
    white: "white",
    black: "black",
    check: "Check",
    checkmate: "Checkmate",
    stalemate: "Stalemate",
    material: "Insufficient material",
    repetition: "Threefold repetition",
    fifty: "Fifty-move rule",
    resignation: "Resignation",
    choosePromotion: "Promote the pawn to",
    queen: "Queen",
    rook: "Rook",
    bishop: "Bishop",
    knight: "Knight",
    sayWin: "{game}: {result} ({side}) · {how} · moves: {n}",
    sayDrawn: "{game}: {result} · {how} · moves: {n}",
  },
  es: {
    name: "Ajedrez",
    board: "Tablero de ajedrez",
    white: "blancas",
    black: "negras",
    check: "Jaque",
    checkmate: "Jaque mate",
    stalemate: "Rey ahogado",
    material: "Material insuficiente",
    repetition: "Triple repetición",
    fifty: "Regla de los 50 movimientos",
    resignation: "Abandono",
    choosePromotion: "Coronar el peón como",
    queen: "Dama",
    rook: "Torre",
    bishop: "Alfil",
    knight: "Caballo",
    sayWin: "{game}: {result} ({side}) · {how} · jugadas: {n}",
    sayDrawn: "{game}: {result} · {how} · jugadas: {n}",
  },
  fr: {
    name: "Échecs",
    board: "Échiquier",
    white: "blancs",
    black: "noirs",
    check: "Échec",
    checkmate: "Échec et mat",
    stalemate: "Pat",
    material: "Matériel insuffisant",
    repetition: "Triple répétition",
    fifty: "Règle des 50 coups",
    resignation: "Abandon",
    choosePromotion: "Promouvoir le pion en",
    queen: "Dame",
    rook: "Tour",
    bishop: "Fou",
    knight: "Cavalier",
    sayWin: "{game} : {result} ({side}) · {how} · coups : {n}",
    sayDrawn: "{game} : {result} · {how} · coups : {n}",
  },
  de: {
    name: "Schach",
    board: "Schachbrett",
    white: "Weiß",
    black: "Schwarz",
    check: "Schach",
    checkmate: "Schachmatt",
    stalemate: "Patt",
    material: "Ungenügendes Material",
    repetition: "Dreifache Stellungswiederholung",
    fifty: "50-Züge-Regel",
    resignation: "Aufgabe",
    choosePromotion: "Bauer umwandeln in",
    queen: "Dame",
    rook: "Turm",
    bishop: "Läufer",
    knight: "Springer",
    sayWin: "{game}: {result} ({side}) · {how} · Züge: {n}",
    sayDrawn: "{game}: {result} · {how} · Züge: {n}",
  },
  it: {
    name: "Scacchi",
    board: "Scacchiera",
    white: "bianco",
    black: "nero",
    check: "Scacco",
    checkmate: "Scacco matto",
    stalemate: "Stallo",
    material: "Materiale insufficiente",
    repetition: "Triplice ripetizione",
    fifty: "Regola delle 50 mosse",
    resignation: "Abbandono",
    choosePromotion: "Promuovi il pedone a",
    queen: "Donna",
    rook: "Torre",
    bishop: "Alfiere",
    knight: "Cavallo",
    sayWin: "{game}: {result} ({side}) · {how} · mosse: {n}",
    sayDrawn: "{game}: {result} · {how} · mosse: {n}",
  },
  pt: {
    name: "Xadrez",
    board: "Tabuleiro de xadrez",
    white: "brancas",
    black: "pretas",
    check: "Xeque",
    checkmate: "Xeque-mate",
    stalemate: "Afogamento",
    material: "Material insuficiente",
    repetition: "Repetição tripla",
    fifty: "Regra dos 50 lances",
    resignation: "Abandono",
    choosePromotion: "Promover o peão a",
    queen: "Dama",
    rook: "Torre",
    bishop: "Bispo",
    knight: "Cavalo",
    sayWin: "{game}: {result} ({side}) · {how} · lances: {n}",
    sayDrawn: "{game}: {result} · {how} · lances: {n}",
  },
  ro: {
    name: "Șah",
    board: "Tablă de șah",
    white: "albe",
    black: "negre",
    check: "Șah",
    checkmate: "Șah mat",
    stalemate: "Pat",
    material: "Material insuficient",
    repetition: "Repetare triplă",
    fifty: "Regula celor 50 de mutări",
    resignation: "Abandon",
    choosePromotion: "Transformă pionul în",
    queen: "Regină",
    rook: "Turn",
    bishop: "Nebun",
    knight: "Cal",
    sayWin: "{game}: {result} ({side}) · {how} · mutări: {n}",
    sayDrawn: "{game}: {result} · {how} · mutări: {n}",
  },
  pl: {
    name: "Szachy",
    board: "Szachownica",
    white: "białe",
    black: "czarne",
    check: "Szach",
    checkmate: "Mat",
    stalemate: "Pat",
    material: "Niewystarczający materiał",
    repetition: "Trzykrotne powtórzenie pozycji",
    fifty: "Zasada 50 posunięć",
    resignation: "Poddanie",
    choosePromotion: "Promuj pionka na",
    queen: "Hetman",
    rook: "Wieża",
    bishop: "Goniec",
    knight: "Skoczek",
    sayWin: "{game}: {result} ({side}) · {how} · posunięcia: {n}",
    sayDrawn: "{game}: {result} · {how} · posunięcia: {n}",
  },
  ru: {
    name: "Шахматы",
    board: "Шахматная доска",
    white: "белые",
    black: "чёрные",
    check: "Шах",
    checkmate: "Мат",
    stalemate: "Пат",
    material: "Недостаточно материала",
    repetition: "Троекратное повторение",
    fifty: "Правило 50 ходов",
    resignation: "Сдача",
    choosePromotion: "Превратить пешку в",
    queen: "Ферзь",
    rook: "Ладья",
    bishop: "Слон",
    knight: "Конь",
    sayWin: "{game}: {result} ({side}) · {how} · ходов: {n}",
    sayDrawn: "{game}: {result} · {how} · ходов: {n}",
  },
  uk: {
    name: "Шахи",
    board: "Шахова дошка",
    white: "білі",
    black: "чорні",
    check: "Шах",
    checkmate: "Мат",
    stalemate: "Пат",
    material: "Недостатньо матеріалу",
    repetition: "Триразове повторення",
    fifty: "Правило 50 ходів",
    resignation: "Здача",
    choosePromotion: "Перетворити пішака на",
    queen: "Ферзь",
    rook: "Тура",
    bishop: "Слон",
    knight: "Кінь",
    sayWin: "{game}: {result} ({side}) · {how} · ходів: {n}",
    sayDrawn: "{game}: {result} · {how} · ходів: {n}",
  },
  tr: {
    name: "Satranç",
    board: "Satranç tahtası",
    white: "beyaz",
    black: "siyah",
    check: "Şah",
    checkmate: "Şah mat",
    stalemate: "Pat",
    material: "Yetersiz materyal",
    repetition: "Üç kez tekrar",
    fifty: "50 hamle kuralı",
    resignation: "Terk",
    choosePromotion: "Piyonu terfi ettir",
    queen: "Vezir",
    rook: "Kale",
    bishop: "Fil",
    knight: "At",
    sayWin: "{game}: {result} ({side}) · {how} · hamle: {n}",
    sayDrawn: "{game}: {result} · {how} · hamle: {n}",
  },
  ar: {
    name: "شطرنج",
    board: "رقعة الشطرنج",
    white: "الأبيض",
    black: "الأسود",
    check: "كش",
    checkmate: "كش مات",
    stalemate: "جمود",
    material: "قطع غير كافية",
    repetition: "تكرار الوضع ثلاث مرات",
    fifty: "قاعدة الخمسين نقلة",
    resignation: "استسلام",
    choosePromotion: "ترقية البيدق إلى",
    queen: "وزير",
    rook: "رخ",
    bishop: "فيل",
    knight: "حصان",
    sayWin: "{game}: {result} ({side}) · {how} · النقلات: {n}",
    sayDrawn: "{game}: {result} · {how} · النقلات: {n}",
  },
  hi: {
    name: "शतरंज",
    board: "शतरंज की बिसात",
    white: "सफ़ेद",
    black: "काला",
    check: "शह",
    checkmate: "शह और मात",
    stalemate: "गतिरोध",
    material: "मोहरे अपर्याप्त",
    repetition: "तीन बार एक ही स्थिति",
    fifty: "50 चालों का नियम",
    resignation: "हार मानी",
    choosePromotion: "प्यादे को बदलें",
    queen: "वज़ीर",
    rook: "हाथी",
    bishop: "ऊँट",
    knight: "घोड़ा",
    sayWin: "{game}: {result} ({side}) · {how} · चालें: {n}",
    sayDrawn: "{game}: {result} · {how} · चालें: {n}",
  },
  bn: {
    name: "দাবা",
    board: "দাবার বোর্ড",
    white: "সাদা",
    black: "কালো",
    check: "কিস্তি",
    checkmate: "কিস্তিমাত",
    stalemate: "অচলাবস্থা",
    material: "ঘুঁটি অপর্যাপ্ত",
    repetition: "একই অবস্থান তিনবার",
    fifty: "৫০ চালের নিয়ম",
    resignation: "হার স্বীকার",
    choosePromotion: "বোড়েকে বদলে করুন",
    queen: "মন্ত্রী",
    rook: "নৌকা",
    bishop: "হাতি",
    knight: "ঘোড়া",
    sayWin: "{game}: {result} ({side}) · {how} · চাল: {n}",
    sayDrawn: "{game}: {result} · {how} · চাল: {n}",
  },
  id: {
    name: "Catur",
    board: "Papan catur",
    white: "putih",
    black: "hitam",
    check: "Skak",
    checkmate: "Skakmat",
    stalemate: "Pat",
    material: "Bidak tidak cukup",
    repetition: "Posisi berulang tiga kali",
    fifty: "Aturan 50 langkah",
    resignation: "Menyerah",
    choosePromotion: "Promosikan pion menjadi",
    queen: "Ratu",
    rook: "Benteng",
    bishop: "Gajah",
    knight: "Kuda",
    sayWin: "{game}: {result} ({side}) · {how} · langkah: {n}",
    sayDrawn: "{game}: {result} · {how} · langkah: {n}",
  },
  vi: {
    name: "Cờ vua",
    board: "Bàn cờ vua",
    white: "trắng",
    black: "đen",
    check: "Chiếu",
    checkmate: "Chiếu hết",
    stalemate: "Hết nước đi",
    material: "Không đủ quân",
    repetition: "Lặp lại ba lần",
    fifty: "Luật 50 nước",
    resignation: "Xin thua",
    choosePromotion: "Phong cấp tốt thành",
    queen: "Hậu",
    rook: "Xe",
    bishop: "Tượng",
    knight: "Mã",
    sayWin: "{game}: {result} ({side}) · {how} · số nước: {n}",
    sayDrawn: "{game}: {result} · {how} · số nước: {n}",
  },
  th: {
    name: "หมากรุกสากล",
    board: "กระดานหมากรุก",
    white: "ขาว",
    black: "ดำ",
    check: "รุก",
    checkmate: "รุกจน",
    stalemate: "อับ",
    material: "หมากไม่พอรุกจน",
    repetition: "ตำแหน่งซ้ำสามครั้ง",
    fifty: "กฎ 50 ตา",
    resignation: "ยอมแพ้",
    choosePromotion: "เลื่อนขั้นเบี้ยเป็น",
    queen: "ควีน",
    rook: "เรือ",
    bishop: "บิชอป",
    knight: "อัศวิน",
    sayWin: "{game}: {result} ({side}) · {how} · ตาเดิน: {n}",
    sayDrawn: "{game}: {result} · {how} · ตาเดิน: {n}",
  },
  ja: {
    name: "チェス",
    board: "チェス盤",
    white: "白",
    black: "黒",
    check: "チェック",
    checkmate: "チェックメイト",
    stalemate: "ステイルメイト",
    material: "駒不足",
    repetition: "同一局面3回",
    fifty: "50手ルール",
    resignation: "投了",
    choosePromotion: "ポーンの昇格先",
    queen: "クイーン",
    rook: "ルーク",
    bishop: "ビショップ",
    knight: "ナイト",
    sayWin: "{game}：{result}（{side}）・{how}・手数：{n}",
    sayDrawn: "{game}：{result}・{how}・手数：{n}",
  },
  ko: {
    name: "체스",
    board: "체스판",
    white: "백",
    black: "흑",
    check: "체크",
    checkmate: "체크메이트",
    stalemate: "스테일메이트",
    material: "기물 부족",
    repetition: "3회 동형 반복",
    fifty: "50수 규칙",
    resignation: "기권",
    choosePromotion: "폰 승진",
    queen: "퀸",
    rook: "룩",
    bishop: "비숍",
    knight: "나이트",
    sayWin: "{game}: {result} ({side}) · {how} · 수: {n}",
    sayDrawn: "{game}: {result} · {how} · 수: {n}",
  },
  "zh-CN": {
    name: "国际象棋",
    board: "国际象棋棋盘",
    white: "白方",
    black: "黑方",
    check: "将军",
    checkmate: "将死",
    stalemate: "逼和",
    material: "子力不足",
    repetition: "三次重复局面",
    fifty: "五十回合规则",
    resignation: "认输",
    choosePromotion: "兵升变为",
    queen: "后",
    rook: "车",
    bishop: "象",
    knight: "马",
    sayWin: "{game}：{result}（{side}）·{how}·回合：{n}",
    sayDrawn: "{game}：{result}·{how}·回合：{n}",
  },
  "zh-TW": {
    name: "西洋棋",
    board: "西洋棋盤",
    white: "白方",
    black: "黑方",
    check: "將軍",
    checkmate: "將死",
    stalemate: "逼和",
    material: "子力不足",
    repetition: "三次重複局面",
    fifty: "五十回合規則",
    resignation: "認輸",
    choosePromotion: "兵升變為",
    queen: "皇后",
    rook: "城堡",
    bishop: "主教",
    knight: "騎士",
    sayWin: "{game}：{result}（{side}）·{how}·回合：{n}",
    sayDrawn: "{game}：{result}·{how}·回合：{n}",
  },
};
