// What Letter Grid adds to the kit's texts, in the 21 languages of the app: its name (its own,
// never the trademark of the boxed game of lettered dice), the grid, the word being built, the
// lists and the scores, and how a round ends. English is the source. Data only (README, "Texts").

export const TEXTS = {
  en: { name: "Letter Grid", grid: "Grid", tile: "{letter}, row {row}, column {col}", undo: "Take a letter back", sayWord: "Say it", pass: "Pass", yourWords: "your words ({n})", theirWords: "their words ({n})", notAWord: "Not in the word list", alreadySaid: "Already said", notOnGrid: "Not on the grid like that", shuffling: "Drawing the letters…", passed: "Both passed: the points decide", gridCheat: "The letters were not drawn as agreed", seedLost: "The draw was lost on this phone; resign and start a new match." },
  es: { name: "Cuadrícula de letras", grid: "Cuadrícula", tile: "{letter}, fila {row}, columna {col}", undo: "Quitar una letra", sayWord: "Decirla", pass: "Pasar", yourWords: "tus palabras ({n})", theirWords: "sus palabras ({n})", notAWord: "No está en la lista de palabras", alreadySaid: "Ya dicha", notOnGrid: "No está así en la cuadrícula", shuffling: "Sacando las letras…", passed: "Los dos pasaron: deciden los puntos", gridCheat: "Las letras no se sacaron como se acordó", seedLost: "El sorteo se perdió en este teléfono; ríndete y empieza otra partida." },
  fr: { name: "Grille de lettres", grid: "Grille", tile: "{letter}, ligne {row}, colonne {col}", undo: "Retirer une lettre", sayWord: "Le dire", pass: "Passer", yourWords: "vos mots ({n})", theirWords: "leurs mots ({n})", notAWord: "Absent de la liste de mots", alreadySaid: "Déjà dit", notOnGrid: "Pas comme ça sur la grille", shuffling: "Tirage des lettres…", passed: "Les deux ont passé : les points décident", gridCheat: "Les lettres n’ont pas été tirées comme convenu", seedLost: "Le tirage a été perdu sur ce téléphone ; abandonnez et commencez une autre partie." },
  de: { name: "Buchstabengitter", grid: "Gitter", tile: "{letter}, Zeile {row}, Spalte {col}", undo: "Einen Buchstaben zurück", sayWord: "Sagen", pass: "Passen", yourWords: "deine Wörter ({n})", theirWords: "ihre Wörter ({n})", notAWord: "Nicht in der Wortliste", alreadySaid: "Schon gesagt", notOnGrid: "So nicht im Gitter", shuffling: "Buchstaben werden gezogen…", passed: "Beide passten: die Punkte entscheiden", gridCheat: "Die Buchstaben wurden nicht wie vereinbart gezogen", seedLost: "Die Ziehung ging auf diesem Telefon verloren; gib auf und beginne eine neue Partie." },
  it: { name: "Griglia di lettere", grid: "Griglia", tile: "{letter}, riga {row}, colonna {col}", undo: "Togli una lettera", sayWord: "Dilla", pass: "Passa", yourWords: "le tue parole ({n})", theirWords: "le loro parole ({n})", notAWord: "Non è nell’elenco delle parole", alreadySaid: "Già detta", notOnGrid: "Non è così nella griglia", shuffling: "Estraggo le lettere…", passed: "Entrambi hanno passato: decidono i punti", gridCheat: "Le lettere non sono state estratte come concordato", seedLost: "L’estrazione è andata persa su questo telefono; arrenditi e inizia un’altra partita." },
  pt: { name: "Grelha de letras", grid: "Grelha", tile: "{letter}, linha {row}, coluna {col}", undo: "Tirar uma letra", sayWord: "Dizê-la", pass: "Passar", yourWords: "as tuas palavras ({n})", theirWords: "as palavras deles ({n})", notAWord: "Não está na lista de palavras", alreadySaid: "Já dita", notOnGrid: "Não está assim na grelha", shuffling: "A tirar as letras…", passed: "Ambos passaram: os pontos decidem", gridCheat: "As letras não foram tiradas como combinado", seedLost: "O sorteio perdeu-se neste telefone; desiste e começa outra partida." },
  ro: { name: "Grilă de litere", grid: "Grilă", tile: "{letter}, rândul {row}, coloana {col}", undo: "Ia o literă înapoi", sayWord: "Spune-l", pass: "Pas", yourWords: "cuvintele tale ({n})", theirWords: "cuvintele lor ({n})", notAWord: "Nu este în lista de cuvinte", alreadySaid: "Spus deja", notOnGrid: "Nu este așa pe grilă", shuffling: "Se trag literele…", passed: "Amândoi au pasat: decid punctele", gridCheat: "Literele nu au fost trase cum s-a convenit", seedLost: "Tragerea s-a pierdut pe acest telefon; predă-te și începe altă partidă." },
  pl: { name: "Siatka liter", grid: "Siatka", tile: "{letter}, wiersz {row}, kolumna {col}", undo: "Cofnij literę", sayWord: "Powiedz", pass: "Pas", yourWords: "twoje słowa ({n})", theirWords: "ich słowa ({n})", notAWord: "Nie ma go na liście słów", alreadySaid: "Już powiedziane", notOnGrid: "Nie ma tak na siatce", shuffling: "Losowanie liter…", passed: "Oboje spasowali: decydują punkty", gridCheat: "Litery nie zostały wylosowane jak uzgodniono", seedLost: "Losowanie przepadło na tym telefonie; poddaj się i zacznij nową partię." },
  ru: { name: "Сетка букв", grid: "Сетка", tile: "{letter}, ряд {row}, столбец {col}", undo: "Убрать букву", sayWord: "Сказать", pass: "Пас", yourWords: "ваши слова ({n})", theirWords: "слова соперника ({n})", notAWord: "Нет в списке слов", alreadySaid: "Уже названо", notOnGrid: "Так на сетке не выходит", shuffling: "Выбираем буквы…", passed: "Оба спасовали: решают очки", gridCheat: "Буквы выбраны не так, как договорились", seedLost: "Жеребьёвка потеряна на этом телефоне; сдайтесь и начните новую партию." },
  uk: { name: "Сітка літер", grid: "Сітка", tile: "{letter}, ряд {row}, стовпець {col}", undo: "Прибрати літеру", sayWord: "Сказати", pass: "Пас", yourWords: "ваші слова ({n})", theirWords: "слова суперника ({n})", notAWord: "Немає у списку слів", alreadySaid: "Уже названо", notOnGrid: "Так на сітці не виходить", shuffling: "Вибираємо літери…", passed: "Обоє спасували: вирішують очки", gridCheat: "Літери вибрано не так, як домовилися", seedLost: "Жеребкування втрачено на цьому телефоні; здайтеся й почніть нову партію." },
  tr: { name: "Harf Izgarası", grid: "Izgara", tile: "{letter}, satır {row}, sütun {col}", undo: "Bir harf geri al", sayWord: "Söyle", pass: "Pas", yourWords: "senin kelimelerin ({n})", theirWords: "onların kelimeleri ({n})", notAWord: "Kelime listesinde yok", alreadySaid: "Zaten söylendi", notOnGrid: "Izgarada böyle çıkmıyor", shuffling: "Harfler çekiliyor…", passed: "İkisi de pas geçti: puanlar belirler", gridCheat: "Harfler anlaşıldığı gibi çekilmedi", seedLost: "Çekiliş bu telefonda kayboldu; pes et ve yeni bir oyun başlat." },
  ar: { name: "شبكة الحروف", grid: "الشبكة", tile: "{letter}، الصف {row}، العمود {col}", undo: "إرجاع حرف", sayWord: "قُلها", pass: "تمرير", yourWords: "كلماتك ({n})", theirWords: "كلماتهم ({n})", notAWord: "ليست في قائمة الكلمات", alreadySaid: "قيلت من قبل", notOnGrid: "ليست هكذا على الشبكة", shuffling: "جارٍ سحب الحروف…", passed: "مرّر الاثنان: النقاط تحسم", gridCheat: "لم تُسحب الحروف كما اتُّفق", seedLost: "ضاع السحب على هذا الهاتف؛ استسلم وابدأ مباراة جديدة." },
  hi: { name: "अक्षर ग्रिड", grid: "ग्रिड", tile: "{letter}, पंक्ति {row}, स्तंभ {col}", undo: "एक अक्षर हटाएँ", sayWord: "बोलें", pass: "पास", yourWords: "आपके शब्द ({n})", theirWords: "उनके शब्द ({n})", notAWord: "शब्द सूची में नहीं है", alreadySaid: "पहले ही कहा गया", notOnGrid: "ग्रिड पर ऐसे नहीं बनता", shuffling: "अक्षर निकाले जा रहे हैं…", passed: "दोनों ने पास किया: अंक तय करते हैं", gridCheat: "अक्षर तय तरीके से नहीं निकाले गए", seedLost: "इस फ़ोन पर ड्रॉ खो गया; हार मानें और नई बाज़ी शुरू करें।" },
  bn: { name: "অক্ষরের গ্রিড", grid: "গ্রিড", tile: "{letter}, সারি {row}, কলাম {col}", undo: "একটি অক্ষর ফেরান", sayWord: "বলুন", pass: "পাস", yourWords: "আপনার শব্দ ({n})", theirWords: "ওদের শব্দ ({n})", notAWord: "শব্দতালিকায় নেই", alreadySaid: "আগেই বলা হয়েছে", notOnGrid: "গ্রিডে এভাবে হয় না", shuffling: "অক্ষর তোলা হচ্ছে…", passed: "দুজনেই পাস করেছে: পয়েন্টে ফয়সালা", gridCheat: "অক্ষর চুক্তিমতো তোলা হয়নি", seedLost: "এই ফোনে ড্র হারিয়ে গেছে; হার মেনে নতুন খেলা শুরু করুন।" },
  id: { name: "Kisi Huruf", grid: "Kisi", tile: "{letter}, baris {row}, kolom {col}", undo: "Hapus satu huruf", sayWord: "Ucapkan", pass: "Lewat", yourWords: "kata Anda ({n})", theirWords: "kata mereka ({n})", notAWord: "Tidak ada dalam daftar kata", alreadySaid: "Sudah diucapkan", notOnGrid: "Tidak begitu di kisi", shuffling: "Mengundi huruf…", passed: "Keduanya lewat: poin yang menentukan", gridCheat: "Huruf tidak diundi seperti yang disepakati", seedLost: "Undian hilang di ponsel ini; menyerahlah dan mulai pertandingan baru." },
  vi: { name: "Lưới chữ", grid: "Lưới", tile: "{letter}, hàng {row}, cột {col}", undo: "Bỏ một chữ", sayWord: "Nói ra", pass: "Bỏ lượt", yourWords: "từ của bạn ({n})", theirWords: "từ của họ ({n})", notAWord: "Không có trong danh sách từ", alreadySaid: "Đã nói rồi", notOnGrid: "Trên lưới không xếp được như vậy", shuffling: "Đang rút chữ…", passed: "Cả hai bỏ lượt: điểm quyết định", gridCheat: "Chữ không được rút như đã thỏa thuận", seedLost: "Lượt rút bị mất trên điện thoại này; hãy đầu hàng và bắt đầu ván mới." },
  th: { name: "ตารางตัวอักษร", grid: "ตาราง", tile: "{letter} แถว {row} คอลัมน์ {col}", undo: "ถอยหนึ่งตัวอักษร", sayWord: "บอกคำ", pass: "ผ่าน", yourWords: "คำของคุณ ({n})", theirWords: "คำของเขา ({n})", notAWord: "ไม่อยู่ในรายการคำ", alreadySaid: "บอกไปแล้ว", notOnGrid: "ไม่ได้อยู่บนตารางแบบนั้น", shuffling: "กำลังสุ่มตัวอักษร…", passed: "ทั้งคู่ผ่าน: คะแนนตัดสิน", gridCheat: "ตัวอักษรไม่ได้ถูกสุ่มตามที่ตกลง", seedLost: "การสุ่มหายไปจากโทรศัพท์เครื่องนี้ ยอมแพ้แล้วเริ่มเกมใหม่" },
  ja: { name: "文字グリッド", grid: "グリッド", tile: "{letter}、{row}行{col}列", undo: "1文字戻す", sayWord: "言う", pass: "パス", yourWords: "あなたの単語（{n}）", theirWords: "相手の単語（{n}）", notAWord: "単語リストにありません", alreadySaid: "すでに言いました", notOnGrid: "グリッド上でそうつながりません", shuffling: "文字を引いています…", passed: "両者パス：得点で決着", gridCheat: "文字が取り決めどおりに引かれていません", seedLost: "抽選がこの端末から失われました。降参して新しい対局を始めてください。" },
  ko: { name: "글자 격자", grid: "격자", tile: "{letter}, {row}행 {col}열", undo: "한 글자 되돌리기", sayWord: "말하기", pass: "패스", yourWords: "내 단어 ({n})", theirWords: "상대 단어 ({n})", notAWord: "단어 목록에 없어요", alreadySaid: "이미 말했어요", notOnGrid: "격자에서 그렇게 이어지지 않아요", shuffling: "글자를 뽑는 중…", passed: "둘 다 패스: 점수로 결정", gridCheat: "약속대로 글자를 뽑지 않았어요", seedLost: "이 휴대폰에서 추첨이 사라졌어요. 기권하고 새 경기를 시작하세요." },
  "zh-CN": { name: "字母格", grid: "格子", tile: "{letter}，第 {row} 行第 {col} 列", undo: "退回一个字母", sayWord: "说出", pass: "过", yourWords: "你的单词（{n}）", theirWords: "对方的单词（{n}）", notAWord: "不在词表中", alreadySaid: "已经说过", notOnGrid: "格子上无法这样连成", shuffling: "抽取字母中…", passed: "双方都过：按得分决定", gridCheat: "字母未按约定抽取", seedLost: "抽取记录已不在这部手机上；请认输并开始新的一局。" },
  "zh-TW": { name: "字母格", grid: "格子", tile: "{letter}，第 {row} 列第 {col} 欄", undo: "退回一個字母", sayWord: "說出", pass: "過", yourWords: "你的單字（{n}）", theirWords: "對方的單字（{n}）", notAWord: "不在詞表中", alreadySaid: "已經說過", notOnGrid: "格子上無法這樣連成", shuffling: "抽取字母中…", passed: "雙方都過：按得分決定", gridCheat: "字母未按約定抽取", seedLost: "抽取紀錄已不在這支手機上；請認輸並開始新的一局。" },
};
