// What checkers adds to the kit's texts, in the 21 languages of the app: its name (the plain name
// of the game in each language), what a screen reader says of the board, the count of pieces, and
// why a round ended. English is the source. Data only (README, "Texts").

export const TEXTS = {
  en: { name: "Checkers", board: "Board", square: "Row {row}, column {col}", empty: "empty", dark: "dark piece", light: "light piece", darkKing: "dark king", lightKing: "light king", count: "{dark} dark, {light} light", noMoves: "No move left", captured: "All pieces taken", quiet: "50 king moves without a capture" },
  es: { name: "Damas", board: "Tablero", square: "Fila {row}, columna {col}", empty: "vacía", dark: "ficha oscura", light: "ficha clara", darkKing: "dama oscura", lightKing: "dama clara", count: "{dark} oscuras, {light} claras", noMoves: "Sin jugadas posibles", captured: "Todas las fichas capturadas", quiet: "50 jugadas de dama sin captura" },
  fr: { name: "Jeu de dames", board: "Damier", square: "Ligne {row}, colonne {col}", empty: "vide", dark: "pion foncé", light: "pion clair", darkKing: "dame foncée", lightKing: "dame claire", count: "{dark} foncés, {light} clairs", noMoves: "Plus aucun coup", captured: "Tous les pions pris", quiet: "50 coups de dame sans prise" },
  de: { name: "Dame", board: "Spielfeld", square: "Zeile {row}, Spalte {col}", empty: "leer", dark: "dunkler Stein", light: "heller Stein", darkKing: "dunkle Dame", lightKing: "helle Dame", count: "{dark} dunkle, {light} helle", noMoves: "Kein Zug mehr möglich", captured: "Alle Steine geschlagen", quiet: "50 Damenzüge ohne Schlagen" },
  it: { name: "Dama", board: "Damiera", square: "Riga {row}, colonna {col}", empty: "vuota", dark: "pedina scura", light: "pedina chiara", darkKing: "dama scura", lightKing: "dama chiara", count: "{dark} scure, {light} chiare", noMoves: "Nessuna mossa possibile", captured: "Tutte le pedine catturate", quiet: "50 mosse di dama senza catture" },
  pt: { name: "Damas", board: "Tabuleiro", square: "Linha {row}, coluna {col}", empty: "vazia", dark: "peça escura", light: "peça clara", darkKing: "dama escura", lightKing: "dama clara", count: "{dark} escuras, {light} claras", noMoves: "Sem jogadas possíveis", captured: "Todas as peças capturadas", quiet: "50 jogadas de dama sem captura" },
  ro: { name: "Dame", board: "Tabla", square: "Rândul {row}, coloana {col}", empty: "goală", dark: "piesă închisă", light: "piesă deschisă", darkKing: "damă închisă", lightKing: "damă deschisă", count: "{dark} închise, {light} deschise", noMoves: "Nicio mutare posibilă", captured: "Toate piesele capturate", quiet: "50 de mutări de damă fără captură" },
  pl: { name: "Warcaby", board: "Plansza", square: "Wiersz {row}, kolumna {col}", empty: "puste", dark: "ciemny pionek", light: "jasny pionek", darkKing: "ciemna damka", lightKing: "jasna damka", count: "{dark} ciemnych, {light} jasnych", noMoves: "Brak możliwych ruchów", captured: "Wszystkie pionki zbite", quiet: "50 ruchów damką bez bicia" },
  ru: { name: "Шашки", board: "Доска", square: "Ряд {row}, столбец {col}", empty: "пусто", dark: "тёмная шашка", light: "светлая шашка", darkKing: "тёмная дамка", lightKing: "светлая дамка", count: "{dark} тёмных, {light} светлых", noMoves: "Ходов не осталось", captured: "Все шашки взяты", quiet: "50 ходов дамкой без взятия" },
  uk: { name: "Шашки", board: "Дошка", square: "Ряд {row}, стовпець {col}", empty: "порожньо", dark: "темна шашка", light: "світла шашка", darkKing: "темна дамка", lightKing: "світла дамка", count: "{dark} темних, {light} світлих", noMoves: "Ходів не лишилося", captured: "Усі шашки взято", quiet: "50 ходів дамкою без взяття" },
  tr: { name: "Dama", board: "Tahta", square: "Satır {row}, sütun {col}", empty: "boş", dark: "koyu taş", light: "açık taş", darkKing: "koyu dama", lightKing: "açık dama", count: "{dark} koyu, {light} açık", noMoves: "Hamle kalmadı", captured: "Tüm taşlar alındı", quiet: "Alma olmadan 50 dama hamlesi" },
  ar: { name: "الضامة", board: "اللوحة", square: "الصف {row}، العمود {col}", empty: "فارغة", dark: "قطعة داكنة", light: "قطعة فاتحة", darkKing: "ملكة داكنة", lightKing: "ملكة فاتحة", count: "{dark} داكنة، {light} فاتحة", noMoves: "لا توجد حركات متبقية", captured: "أُخذت كل القطع", quiet: "50 حركة ملكة دون أخذ" },
  hi: { name: "चेकर्स", board: "बोर्ड", square: "पंक्ति {row}, स्तंभ {col}", empty: "खाली", dark: "गहरी गोटी", light: "हल्की गोटी", darkKing: "गहरा राजा", lightKing: "हल्का राजा", count: "{dark} गहरी, {light} हल्की", noMoves: "कोई चाल बाकी नहीं", captured: "सारी गोटियाँ पकड़ी गईं", quiet: "बिना पकड़ के राजा की 50 चालें" },
  bn: { name: "চেকার্স", board: "বোর্ড", square: "সারি {row}, কলাম {col}", empty: "খালি", dark: "গাঢ় গুটি", light: "হালকা গুটি", darkKing: "গাঢ় রাজা", lightKing: "হালকা রাজা", count: "{dark} গাঢ়, {light} হালকা", noMoves: "আর কোনো চাল নেই", captured: "সব গুটি নেওয়া হয়েছে", quiet: "না খেয়ে রাজার ৫০ চাল" },
  id: { name: "Dam", board: "Papan", square: "Baris {row}, kolom {col}", empty: "kosong", dark: "bidak gelap", light: "bidak terang", darkKing: "raja gelap", lightKing: "raja terang", count: "{dark} gelap, {light} terang", noMoves: "Tidak ada langkah lagi", captured: "Semua bidak dimakan", quiet: "50 langkah raja tanpa makan" },
  vi: { name: "Cờ đam", board: "Bàn cờ", square: "Hàng {row}, cột {col}", empty: "trống", dark: "quân đen", light: "quân trắng", darkKing: "vua đen", lightKing: "vua trắng", count: "{dark} đen, {light} trắng", noMoves: "Không còn nước đi", captured: "Bị ăn hết quân", quiet: "50 nước đi của vua không ăn quân" },
  th: { name: "หมากฮอส", board: "กระดาน", square: "แถว {row} คอลัมน์ {col}", empty: "ว่าง", dark: "หมากดำ", light: "หมากขาว", darkKing: "ฮอสดำ", lightKing: "ฮอสขาว", count: "ดำ {dark} ขาว {light}", noMoves: "ไม่มีตาเดินเหลือ", captured: "หมากถูกกินหมด", quiet: "เดินฮอส 50 ตาโดยไม่กิน" },
  ja: { name: "チェッカー", board: "盤面", square: "{row}行{col}列", empty: "空き", dark: "黒の駒", light: "白の駒", darkKing: "黒のキング", lightKing: "白のキング", count: "黒 {dark}、白 {light}", noMoves: "動かせる手がありません", captured: "駒がすべて取られました", quiet: "取らずにキングが50手" },
  ko: { name: "체커", board: "판", square: "{row}행 {col}열", empty: "비어 있음", dark: "검은 말", light: "흰 말", darkKing: "검은 왕", lightKing: "흰 왕", count: "검은색 {dark}, 흰색 {light}", noMoves: "둘 수 있는 수가 없음", captured: "말을 모두 잃음", quiet: "잡지 않고 왕이 50수" },
  "zh-CN": { name: "西洋跳棋", board: "棋盘", square: "第 {row} 行第 {col} 列", empty: "空", dark: "黑子", light: "白子", darkKing: "黑王", lightKing: "白王", count: "黑 {dark}，白 {light}", noMoves: "无子可动", captured: "棋子全被吃掉", quiet: "王走 50 步未吃子" },
  "zh-TW": { name: "西洋跳棋", board: "棋盤", square: "第 {row} 列第 {col} 欄", empty: "空", dark: "黑子", light: "白子", darkKing: "黑王", lightKing: "白王", count: "黑 {dark}，白 {light}", noMoves: "無子可動", captured: "棋子全被吃掉", quiet: "王走 50 步未吃子" },
};
