// What Crazy Eights adds to the kit's texts, in the 21 languages of the app: its name (the plain
// name of the old card game, never the trademark of a boxed one), the cards, the hands, the
// stock, the suit picker and how a round ends. English is the source. Data only (README, "Texts").

export const TEXTS = {
  en: { name: "Crazy Eights", yourHand: "Your hand: {n} cards", theirHand: "{n} cards", drawPile: "Draw a card ({n} left)", passTurn: "Pass", pickSuit: "Pick a suit", spades: "spades", hearts: "hearts", diamonds: "diamonds", clubs: "clubs", ace: "ace", jack: "jack", queen: "queen", king: "king", cardOf: "{rank} of {suit}", playCard: "Play the {card}", onTable: "On the table: {card}", suitNow: "Suit to follow: {suit}", shuffling: "Shuffling the deck…", wentOut: "All cards played", stuck: "No cards left to draw: fewer cards wins", deckCheat: "The deck was not shuffled as agreed", seedLost: "The shuffle was lost on this phone; resign and start a new match." },
  es: { name: "Ochos locos", yourHand: "Tu mano: {n} cartas", theirHand: "{n} cartas", drawPile: "Robar una carta (quedan {n})", passTurn: "Pasar", pickSuit: "Elige un palo", spades: "picas", hearts: "corazones", diamonds: "diamantes", clubs: "tréboles", ace: "as", jack: "jota", queen: "reina", king: "rey", cardOf: "{rank} de {suit}", playCard: "Jugar el {card}", onTable: "En la mesa: {card}", suitNow: "Palo a seguir: {suit}", shuffling: "Barajando…", wentOut: "Todas las cartas jugadas", stuck: "No quedan cartas que robar: gana quien tiene menos", deckCheat: "La baraja no se mezcló como se acordó", seedLost: "La mezcla se perdió en este teléfono; ríndete y empieza otra partida." },
  fr: { name: "Huit américain", yourHand: "Votre main : {n} cartes", theirHand: "{n} cartes", drawPile: "Piocher une carte ({n} restantes)", passTurn: "Passer", pickSuit: "Choisissez une couleur", spades: "pique", hearts: "cœur", diamonds: "carreau", clubs: "trèfle", ace: "as", jack: "valet", queen: "dame", king: "roi", cardOf: "{rank} de {suit}", playCard: "Jouer le {card}", onTable: "Sur la table : {card}", suitNow: "Couleur à suivre : {suit}", shuffling: "Mélange des cartes…", wentOut: "Toutes les cartes jouées", stuck: "Plus rien à piocher : le moins de cartes gagne", deckCheat: "Le jeu n’a pas été mélangé comme convenu", seedLost: "Le mélange a été perdu sur ce téléphone ; abandonnez et commencez une autre partie." },
  de: { name: "Verrückte Achten", yourHand: "Deine Hand: {n} Karten", theirHand: "{n} Karten", drawPile: "Eine Karte ziehen ({n} übrig)", passTurn: "Passen", pickSuit: "Wähle eine Farbe", spades: "Pik", hearts: "Herz", diamonds: "Karo", clubs: "Kreuz", ace: "Ass", jack: "Bube", queen: "Dame", king: "König", cardOf: "{suit} {rank}", playCard: "{card} spielen", onTable: "Auf dem Tisch: {card}", suitNow: "Zu bedienen: {suit}", shuffling: "Karten werden gemischt…", wentOut: "Alle Karten gespielt", stuck: "Nichts mehr zu ziehen: weniger Karten gewinnen", deckCheat: "Das Blatt wurde nicht wie vereinbart gemischt", seedLost: "Das Mischen ging auf diesem Telefon verloren; gib auf und beginne eine neue Partie." },
  it: { name: "Otto matto", yourHand: "La tua mano: {n} carte", theirHand: "{n} carte", drawPile: "Pesca una carta ({n} rimaste)", passTurn: "Passa", pickSuit: "Scegli un seme", spades: "picche", hearts: "cuori", diamonds: "quadri", clubs: "fiori", ace: "asso", jack: "fante", queen: "regina", king: "re", cardOf: "{rank} di {suit}", playCard: "Gioca il {card}", onTable: "Sul tavolo: {card}", suitNow: "Seme da seguire: {suit}", shuffling: "Mescolo le carte…", wentOut: "Tutte le carte giocate", stuck: "Niente più da pescare: vince chi ha meno carte", deckCheat: "Il mazzo non è stato mescolato come concordato", seedLost: "La mescolata è andata persa su questo telefono; arrenditi e inizia un’altra partita." },
  pt: { name: "Oitos malucos", yourHand: "A tua mão: {n} cartas", theirHand: "{n} cartas", drawPile: "Comprar uma carta (faltam {n})", passTurn: "Passar", pickSuit: "Escolhe um naipe", spades: "espadas", hearts: "copas", diamonds: "ouros", clubs: "paus", ace: "ás", jack: "valete", queen: "dama", king: "rei", cardOf: "{rank} de {suit}", playCard: "Jogar o {card}", onTable: "Na mesa: {card}", suitNow: "Naipe a seguir: {suit}", shuffling: "A baralhar…", wentOut: "Todas as cartas jogadas", stuck: "Não há mais cartas para comprar: ganha quem tem menos", deckCheat: "O baralho não foi baralhado como combinado", seedLost: "A baralhada perdeu-se neste telefone; desiste e começa outra partida." },
  ro: { name: "Optarii nebuni", yourHand: "Mâna ta: {n} cărți", theirHand: "{n} cărți", drawPile: "Trage o carte ({n} rămase)", passTurn: "Pas", pickSuit: "Alege o culoare", spades: "pică", hearts: "inimă", diamonds: "romb", clubs: "treflă", ace: "as", jack: "valet", queen: "damă", king: "rege", cardOf: "{rank} de {suit}", playCard: "Joacă {card}", onTable: "Pe masă: {card}", suitNow: "Culoarea de urmat: {suit}", shuffling: "Se amestecă…", wentOut: "Toate cărțile jucate", stuck: "Nu mai sunt cărți de tras: câștigă cine are mai puține", deckCheat: "Pachetul nu a fost amestecat cum s-a convenit", seedLost: "Amestecarea s-a pierdut pe acest telefon; predă-te și începe altă partidă." },
  pl: { name: "Szalone ósemki", yourHand: "Twoja ręka: {n} kart", theirHand: "{n} kart", drawPile: "Dobierz kartę (zostało {n})", passTurn: "Pas", pickSuit: "Wybierz kolor", spades: "pik", hearts: "kier", diamonds: "karo", clubs: "trefl", ace: "as", jack: "walet", queen: "dama", king: "król", cardOf: "{rank} {suit}", playCard: "Zagraj {card}", onTable: "Na stole: {card}", suitNow: "Kolor do zagrania: {suit}", shuffling: "Tasowanie…", wentOut: "Wszystkie karty zagrane", stuck: "Nie ma już kart do dobrania: wygrywa mniej kart", deckCheat: "Talia nie została potasowana jak uzgodniono", seedLost: "Tasowanie przepadło na tym telefonie; poddaj się i zacznij nową partię." },
  ru: { name: "Сумасшедшие восьмёрки", yourHand: "Ваша рука: карт — {n}", theirHand: "Карт: {n}", drawPile: "Взять карту (осталось {n})", passTurn: "Пас", pickSuit: "Выберите масть", spades: "пики", hearts: "червы", diamonds: "бубны", clubs: "трефы", ace: "туз", jack: "валет", queen: "дама", king: "король", cardOf: "{rank}, {suit}", playCard: "Сыграть: {card}", onTable: "На столе: {card}", suitNow: "Масть: {suit}", shuffling: "Тасуем колоду…", wentOut: "Все карты сыграны", stuck: "Брать нечего: побеждает тот, у кого меньше карт", deckCheat: "Колода перетасована не так, как договорились", seedLost: "Тасовка потеряна на этом телефоне; сдайтесь и начните новую партию." },
  uk: { name: "Божевільні вісімки", yourHand: "Ваша рука: карт — {n}", theirHand: "Карт: {n}", drawPile: "Взяти карту (лишилося {n})", passTurn: "Пас", pickSuit: "Виберіть масть", spades: "піки", hearts: "чирви", diamonds: "бубни", clubs: "трефи", ace: "туз", jack: "валет", queen: "дама", king: "король", cardOf: "{rank}, {suit}", playCard: "Зіграти: {card}", onTable: "На столі: {card}", suitNow: "Масть: {suit}", shuffling: "Тасуємо колоду…", wentOut: "Усі карти зіграно", stuck: "Брати нічого: перемагає той, у кого менше карт", deckCheat: "Колоду перетасовано не так, як домовилися", seedLost: "Тасування втрачено на цьому телефоні; здайтеся й почніть нову партію." },
  tr: { name: "Çılgın Sekizler", yourHand: "Elin: {n} kart", theirHand: "{n} kart", drawPile: "Kart çek ({n} kaldı)", passTurn: "Pas", pickSuit: "Bir renk seç", spades: "maça", hearts: "kupa", diamonds: "karo", clubs: "sinek", ace: "as", jack: "vale", queen: "kız", king: "papaz", cardOf: "{suit} {rank}", playCard: "{card} oyna", onTable: "Masada: {card}", suitNow: "Uyulacak renk: {suit}", shuffling: "Deste karılıyor…", wentOut: "Bütün kartlar oynandı", stuck: "Çekilecek kart kalmadı: az kartı olan kazanır", deckCheat: "Deste anlaşıldığı gibi karılmadı", seedLost: "Karma bu telefonda kayboldu; pes et ve yeni bir oyun başlat." },
  ar: { name: "الثمانيات المجنونة", yourHand: "يدك: {n} أوراق", theirHand: "{n} أوراق", drawPile: "اسحب ورقة (بقي {n})", passTurn: "تمرير", pickSuit: "اختر نوعًا", spades: "بستوني", hearts: "قلوب", diamonds: "ديناري", clubs: "سباتي", ace: "آس", jack: "ولد", queen: "بنت", king: "ملك", cardOf: "{rank} {suit}", playCard: "لعب {card}", onTable: "على الطاولة: {card}", suitNow: "النوع المطلوب: {suit}", shuffling: "جارٍ خلط الأوراق…", wentOut: "لُعبت كل الأوراق", stuck: "لم يبق ما يُسحب: يفوز من أوراقه أقل", deckCheat: "لم تُخلط الأوراق كما اتُّفق", seedLost: "ضاع الخلط على هذا الهاتف؛ استسلم وابدأ مباراة جديدة." },
  hi: { name: "क्रेज़ी एट्स", yourHand: "आपके पत्ते: {n}", theirHand: "{n} पत्ते", drawPile: "एक पत्ता उठाएँ ({n} बचे)", passTurn: "पास", pickSuit: "एक रंग चुनें", spades: "हुकुम", hearts: "पान", diamonds: "ईंट", clubs: "चिड़ी", ace: "इक्का", jack: "गुलाम", queen: "बेगम", king: "बादशाह", cardOf: "{suit} का {rank}", playCard: "{card} खेलें", onTable: "मेज़ पर: {card}", suitNow: "चलने का रंग: {suit}", shuffling: "पत्ते फेंटे जा रहे हैं…", wentOut: "सारे पत्ते खेल दिए", stuck: "उठाने को पत्ते नहीं बचे: कम पत्तों वाला जीतता है", deckCheat: "गड्डी तय तरीके से नहीं फेंटी गई", seedLost: "इस फ़ोन पर फेंटना खो गया; हार मानें और नई बाज़ी शुरू करें।" },
  bn: { name: "ক্রেজি এইটস", yourHand: "আপনার হাত: {n}টি কার্ড", theirHand: "{n}টি কার্ড", drawPile: "একটি কার্ড তুলুন ({n} বাকি)", passTurn: "পাস", pickSuit: "একটি রং বাছুন", spades: "ইস্কাপন", hearts: "হরতন", diamonds: "রুইতন", clubs: "চিড়িতন", ace: "টেক্কা", jack: "গোলাম", queen: "বিবি", king: "সাহেব", cardOf: "{suit}ের {rank}", playCard: "{card} খেলুন", onTable: "টেবিলে: {card}", suitNow: "চলার রং: {suit}", shuffling: "কার্ড ফেটানো হচ্ছে…", wentOut: "সব কার্ড খেলা হয়েছে", stuck: "তোলার কার্ড নেই: কম কার্ড যার, সে জেতে", deckCheat: "কার্ড চুক্তিমতো ফেটানো হয়নি", seedLost: "এই ফোনে ফেটানো হারিয়ে গেছে; হার মেনে নতুন খেলা শুরু করুন।" },
  id: { name: "Delapan Gila", yourHand: "Tangan Anda: {n} kartu", theirHand: "{n} kartu", drawPile: "Ambil kartu (sisa {n})", passTurn: "Lewat", pickSuit: "Pilih jenis", spades: "sekop", hearts: "hati", diamonds: "wajik", clubs: "keriting", ace: "as", jack: "jack", queen: "ratu", king: "raja", cardOf: "{rank} {suit}", playCard: "Mainkan {card}", onTable: "Di meja: {card}", suitNow: "Jenis yang diikuti: {suit}", shuffling: "Mengocok kartu…", wentOut: "Semua kartu dimainkan", stuck: "Tidak ada kartu untuk diambil: kartu lebih sedikit menang", deckCheat: "Kartu tidak dikocok seperti yang disepakati", seedLost: "Kocokan hilang di ponsel ini; menyerahlah dan mulai pertandingan baru." },
  vi: { name: "Tám điên", yourHand: "Bài của bạn: {n} lá", theirHand: "{n} lá", drawPile: "Rút một lá (còn {n})", passTurn: "Bỏ lượt", pickSuit: "Chọn chất", spades: "bích", hearts: "cơ", diamonds: "rô", clubs: "chuồn", ace: "át", jack: "bồi", queen: "đầm", king: "già", cardOf: "{rank} {suit}", playCard: "Đánh {card}", onTable: "Trên bàn: {card}", suitNow: "Chất phải theo: {suit}", shuffling: "Đang xáo bài…", wentOut: "Đã đánh hết bài", stuck: "Hết bài để rút: ít bài hơn thắng", deckCheat: "Bộ bài không được xáo như đã thỏa thuận", seedLost: "Lượt xáo bị mất trên điện thoại này; hãy đầu hàng và bắt đầu ván mới." },
  th: { name: "แปดบ้า", yourHand: "ไพ่ในมือ: {n} ใบ", theirHand: "{n} ใบ", drawPile: "จั่วไพ่ (เหลือ {n})", passTurn: "ผ่าน", pickSuit: "เลือกดอก", spades: "โพดำ", hearts: "โพแดง", diamonds: "ข้าวหลามตัด", clubs: "ดอกจิก", ace: "เอซ", jack: "แจ็ค", queen: "ควีน", king: "คิง", cardOf: "{rank} {suit}", playCard: "ลง {card}", onTable: "บนโต๊ะ: {card}", suitNow: "ดอกที่ต้องตาม: {suit}", shuffling: "กำลังสับไพ่…", wentOut: "ลงไพ่หมดแล้ว", stuck: "ไม่มีไพ่ให้จั่ว: ใครมีไพ่น้อยกว่าชนะ", deckCheat: "ไพ่ไม่ได้ถูกสับตามที่ตกลง", seedLost: "การสับไพ่หายไปจากโทรศัพท์เครื่องนี้ ยอมแพ้แล้วเริ่มเกมใหม่" },
  ja: { name: "クレイジーエイト", yourHand: "手札：{n} 枚", theirHand: "{n} 枚", drawPile: "1枚引く（残り {n}）", passTurn: "パス", pickSuit: "スートを選ぶ", spades: "スペード", hearts: "ハート", diamonds: "ダイヤ", clubs: "クラブ", ace: "エース", jack: "ジャック", queen: "クイーン", king: "キング", cardOf: "{suit}の{rank}", playCard: "{card}を出す", onTable: "場：{card}", suitNow: "続けるスート：{suit}", shuffling: "シャッフル中…", wentOut: "手札をすべて出した", stuck: "山札がなくなった：手札が少ない方の勝ち", deckCheat: "山札が取り決めどおりに混ぜられていません", seedLost: "シャッフルがこの端末から失われました。降参して新しい対局を始めてください。" },
  ko: { name: "크레이지 에이트", yourHand: "내 패: {n}장", theirHand: "{n}장", drawPile: "한 장 뽑기 ({n}장 남음)", passTurn: "패스", pickSuit: "무늬 고르기", spades: "스페이드", hearts: "하트", diamonds: "다이아몬드", clubs: "클럽", ace: "에이스", jack: "잭", queen: "퀸", king: "킹", cardOf: "{suit} {rank}", playCard: "{card} 내기", onTable: "테이블: {card}", suitNow: "따라야 할 무늬: {suit}", shuffling: "카드를 섞는 중…", wentOut: "카드를 모두 냈어요", stuck: "뽑을 카드가 없어요: 카드가 적은 쪽이 이겨요", deckCheat: "약속대로 카드를 섞지 않았어요", seedLost: "이 휴대폰에서 섞기가 사라졌어요. 기권하고 새 경기를 시작하세요." },
  "zh-CN": { name: "疯狂八", yourHand: "你的手牌：{n} 张", theirHand: "{n} 张", drawPile: "摸一张（剩 {n}）", passTurn: "过", pickSuit: "选择花色", spades: "黑桃", hearts: "红桃", diamonds: "方块", clubs: "梅花", ace: "A", jack: "J", queen: "Q", king: "K", cardOf: "{suit}{rank}", playCard: "打出{card}", onTable: "桌面：{card}", suitNow: "须跟花色：{suit}", shuffling: "洗牌中…", wentOut: "手牌已全部打出", stuck: "无牌可摸：手牌少者胜", deckCheat: "牌未按约定洗过", seedLost: "洗牌记录已不在这部手机上；请认输并开始新的一局。" },
  "zh-TW": { name: "瘋狂八", yourHand: "你的手牌：{n} 張", theirHand: "{n} 張", drawPile: "抽一張（剩 {n}）", passTurn: "過", pickSuit: "選擇花色", spades: "黑桃", hearts: "紅心", diamonds: "方塊", clubs: "梅花", ace: "A", jack: "J", queen: "Q", king: "K", cardOf: "{suit}{rank}", playCard: "打出{card}", onTable: "桌面：{card}", suitNow: "須跟花色：{suit}", shuffling: "洗牌中…", wentOut: "手牌已全部打出", stuck: "無牌可抽：手牌少者勝", deckCheat: "牌未按約定洗過", seedLost: "洗牌紀錄已不在這支手機上；請認輸並開始新的一局。" },
};
