// What Sea Battle adds to the kit's texts, in the 21 languages of the app: its name (the plain
// name of the pencil-and-paper game, never the trademark of a boxed one), what a screen reader
// says of the two seas, the placing of the fleet, the answers, and how a round ends. English is
// the source. Data only (README, "Texts").

export const TEXTS = {
  en: { name: "Sea Battle", yourSea: "Your sea", theirSea: "Their sea", cell: "Row {row}, column {col}", water: "water", ship: "ship", unknown: "not fired at", miss: "miss", hit: "hit", sunk: "sunk", shuffle: "Shuffle", ready: "Ready", placeFleet: "Place your five ships, then tap Ready. Your fleet stays on this phone.", fleetWait: "Waiting for the other fleet", fleetLost: "Your fleet is no longer on this phone; resign and start a new match.", fireAt: "Fire at row {row}, column {col}", shipsLeft: "{n} ships afloat", allSunk: "The whole fleet was sunk", dishonest: "A fleet did not match its answers", bothDishonest: "Neither fleet matched its answers" },
  es: { name: "Batalla naval", yourSea: "Tu mar", theirSea: "Su mar", cell: "Fila {row}, columna {col}", water: "agua", ship: "barco", unknown: "sin disparar", miss: "agua", hit: "tocado", sunk: "hundido", shuffle: "Barajar", ready: "Listo", placeFleet: "Coloca tus cinco barcos y pulsa Listo. Tu flota se queda en este teléfono.", fleetWait: "Esperando la otra flota", fleetLost: "Tu flota ya no está en este teléfono; ríndete y empieza otra partida.", fireAt: "Disparar a la fila {row}, columna {col}", shipsLeft: "{n} barcos a flote", allSunk: "Toda la flota hundida", dishonest: "Una flota no coincidía con sus respuestas", bothDishonest: "Ninguna flota coincidía con sus respuestas" },
  fr: { name: "Bataille navale", yourSea: "Votre mer", theirSea: "Leur mer", cell: "Ligne {row}, colonne {col}", water: "eau", ship: "navire", unknown: "pas encore visé", miss: "à l’eau", hit: "touché", sunk: "coulé", shuffle: "Mélanger", ready: "Prêt", placeFleet: "Placez vos cinq navires, puis touchez Prêt. Votre flotte reste sur ce téléphone.", fleetWait: "En attente de l’autre flotte", fleetLost: "Votre flotte n’est plus sur ce téléphone ; abandonnez et commencez une autre partie.", fireAt: "Tirer sur la ligne {row}, colonne {col}", shipsLeft: "{n} navires à flot", allSunk: "Toute la flotte a été coulée", dishonest: "Une flotte ne correspondait pas à ses réponses", bothDishonest: "Aucune flotte ne correspondait à ses réponses" },
  de: { name: "Seeschlacht", yourSea: "Dein Meer", theirSea: "Ihr Meer", cell: "Zeile {row}, Spalte {col}", water: "Wasser", ship: "Schiff", unknown: "noch nicht beschossen", miss: "Wasser", hit: "Treffer", sunk: "versenkt", shuffle: "Mischen", ready: "Bereit", placeFleet: "Setze deine fünf Schiffe und tippe auf Bereit. Deine Flotte bleibt auf diesem Telefon.", fleetWait: "Warten auf die andere Flotte", fleetLost: "Deine Flotte ist nicht mehr auf diesem Telefon; gib auf und beginne eine neue Partie.", fireAt: "Auf Zeile {row}, Spalte {col} schießen", shipsLeft: "{n} Schiffe schwimmen noch", allSunk: "Die ganze Flotte wurde versenkt", dishonest: "Eine Flotte passte nicht zu ihren Antworten", bothDishonest: "Keine Flotte passte zu ihren Antworten" },
  it: { name: "Battaglia navale", yourSea: "Il tuo mare", theirSea: "Il loro mare", cell: "Riga {row}, colonna {col}", water: "acqua", ship: "nave", unknown: "non colpita", miss: "acqua", hit: "colpito", sunk: "affondato", shuffle: "Mescola", ready: "Pronto", placeFleet: "Disponi le tue cinque navi e tocca Pronto. La tua flotta resta su questo telefono.", fleetWait: "In attesa dell’altra flotta", fleetLost: "La tua flotta non è più su questo telefono; arrenditi e inizia un’altra partita.", fireAt: "Spara alla riga {row}, colonna {col}", shipsLeft: "{n} navi a galla", allSunk: "Tutta la flotta è stata affondata", dishonest: "Una flotta non corrispondeva alle sue risposte", bothDishonest: "Nessuna flotta corrispondeva alle sue risposte" },
  pt: { name: "Batalha naval", yourSea: "O teu mar", theirSea: "O mar deles", cell: "Linha {row}, coluna {col}", water: "água", ship: "navio", unknown: "sem disparo", miss: "água", hit: "acertou", sunk: "afundado", shuffle: "Baralhar", ready: "Pronto", placeFleet: "Coloca os teus cinco navios e toca em Pronto. A tua frota fica neste telefone.", fleetWait: "À espera da outra frota", fleetLost: "A tua frota já não está neste telefone; desiste e começa outra partida.", fireAt: "Disparar à linha {row}, coluna {col}", shipsLeft: "{n} navios a flutuar", allSunk: "Toda a frota foi afundada", dishonest: "Uma frota não correspondia às suas respostas", bothDishonest: "Nenhuma frota correspondia às suas respostas" },
  ro: { name: "Bătălie navală", yourSea: "Marea ta", theirSea: "Marea lor", cell: "Rândul {row}, coloana {col}", water: "apă", ship: "navă", unknown: "fără tragere", miss: "apă", hit: "lovit", sunk: "scufundat", shuffle: "Amestecă", ready: "Gata", placeFleet: "Așază-ți cele cinci nave și apasă Gata. Flota ta rămâne pe acest telefon.", fleetWait: "Se așteaptă cealaltă flotă", fleetLost: "Flota ta nu mai este pe acest telefon; predă-te și începe altă partidă.", fireAt: "Trage la rândul {row}, coloana {col}", shipsLeft: "{n} nave pe apă", allSunk: "Toată flota a fost scufundată", dishonest: "O flotă nu se potrivea cu răspunsurile ei", bothDishonest: "Nicio flotă nu se potrivea cu răspunsurile ei" },
  pl: { name: "Bitwa morska", yourSea: "Twoje morze", theirSea: "Ich morze", cell: "Wiersz {row}, kolumna {col}", water: "woda", ship: "okręt", unknown: "nieostrzelane", miss: "pudło", hit: "trafiony", sunk: "zatopiony", shuffle: "Losuj", ready: "Gotowe", placeFleet: "Ustaw pięć okrętów i dotknij Gotowe. Twoja flota zostaje na tym telefonie.", fleetWait: "Czekanie na drugą flotę", fleetLost: "Twojej floty nie ma już na tym telefonie; poddaj się i zacznij nową partię.", fireAt: "Strzel w wiersz {row}, kolumnę {col}", shipsLeft: "Okrętów na wodzie: {n}", allSunk: "Cała flota została zatopiona", dishonest: "Flota nie zgadzała się z odpowiedziami", bothDishonest: "Żadna flota nie zgadzała się z odpowiedziami" },
  ru: { name: "Морской бой", yourSea: "Ваше море", theirSea: "Их море", cell: "Ряд {row}, столбец {col}", water: "вода", ship: "корабль", unknown: "без выстрела", miss: "мимо", hit: "ранен", sunk: "убит", shuffle: "Расставить", ready: "Готово", placeFleet: "Расставьте пять кораблей и нажмите «Готово». Ваш флот остаётся на этом телефоне.", fleetWait: "Ожидание флота соперника", fleetLost: "Вашего флота больше нет на этом телефоне; сдайтесь и начните новую партию.", fireAt: "Выстрел: ряд {row}, столбец {col}", shipsLeft: "На плаву: {n}", allSunk: "Весь флот потоплен", dishonest: "Флот не совпал со своими ответами", bothDishonest: "Ни один флот не совпал со своими ответами" },
  uk: { name: "Морський бій", yourSea: "Ваше море", theirSea: "Їхнє море", cell: "Ряд {row}, стовпець {col}", water: "вода", ship: "корабель", unknown: "без пострілу", miss: "повз", hit: "поранено", sunk: "потоплено", shuffle: "Розставити", ready: "Готово", placeFleet: "Розставте п’ять кораблів і натисніть «Готово». Ваш флот лишається на цьому телефоні.", fleetWait: "Очікування флоту суперника", fleetLost: "Вашого флоту вже немає на цьому телефоні; здайтеся й почніть нову партію.", fireAt: "Постріл: ряд {row}, стовпець {col}", shipsLeft: "На плаву: {n}", allSunk: "Увесь флот потоплено", dishonest: "Флот не збігся зі своїми відповідями", bothDishonest: "Жоден флот не збігся зі своїми відповідями" },
  tr: { name: "Deniz Savaşı", yourSea: "Senin denizin", theirSea: "Onların denizi", cell: "Satır {row}, sütun {col}", water: "su", ship: "gemi", unknown: "ateş edilmedi", miss: "ıska", hit: "isabet", sunk: "battı", shuffle: "Karıştır", ready: "Hazır", placeFleet: "Beş gemini yerleştir ve Hazır’a dokun. Filon bu telefonda kalır.", fleetWait: "Diğer filo bekleniyor", fleetLost: "Filon artık bu telefonda değil; pes et ve yeni bir oyun başlat.", fireAt: "{row}. satır, {col}. sütuna ateş et", shipsLeft: "{n} gemi yüzüyor", allSunk: "Bütün filo batırıldı", dishonest: "Bir filo verdiği yanıtlarla uyuşmadı", bothDishonest: "Hiçbir filo verdiği yanıtlarla uyuşmadı" },
  ar: { name: "معركة بحرية", yourSea: "بحرك", theirSea: "بحرهم", cell: "الصف {row}، العمود {col}", water: "ماء", ship: "سفينة", unknown: "لم يُطلق عليها", miss: "ماء", hit: "إصابة", sunk: "غرقت", shuffle: "خلط", ready: "جاهز", placeFleet: "ضع سفنك الخمس ثم اضغط جاهز. يبقى أسطولك على هذا الهاتف.", fleetWait: "بانتظار الأسطول الآخر", fleetLost: "لم يعد أسطولك على هذا الهاتف؛ استسلم وابدأ مباراة جديدة.", fireAt: "إطلاق على الصف {row}، العمود {col}", shipsLeft: "{n} سفن طافية", allSunk: "غرق الأسطول كله", dishonest: "أسطول لم يطابق إجاباته", bothDishonest: "لم يطابق أي أسطول إجاباته" },
  hi: { name: "समुद्री युद्ध", yourSea: "आपका समुद्र", theirSea: "उनका समुद्र", cell: "पंक्ति {row}, स्तंभ {col}", water: "पानी", ship: "जहाज़", unknown: "अभी निशाना नहीं", miss: "चूक", hit: "लगा", sunk: "डूबा", shuffle: "फेरबदल", ready: "तैयार", placeFleet: "अपने पाँच जहाज़ रखें और तैयार दबाएँ। आपका बेड़ा इसी फ़ोन पर रहता है।", fleetWait: "दूसरे बेड़े का इंतज़ार", fleetLost: "आपका बेड़ा अब इस फ़ोन पर नहीं है; हार मानें और नई बाज़ी शुरू करें।", fireAt: "पंक्ति {row}, स्तंभ {col} पर गोला दागें", shipsLeft: "{n} जहाज़ तैर रहे हैं", allSunk: "पूरा बेड़ा डूब गया", dishonest: "एक बेड़ा अपने जवाबों से मेल नहीं खाता था", bothDishonest: "कोई भी बेड़ा अपने जवाबों से मेल नहीं खाता था" },
  bn: { name: "নৌযুদ্ধ", yourSea: "আপনার সমুদ্র", theirSea: "ওদের সমুদ্র", cell: "সারি {row}, কলাম {col}", water: "জল", ship: "জাহাজ", unknown: "গুলি হয়নি", miss: "ফসকে গেছে", hit: "লেগেছে", sunk: "ডুবেছে", shuffle: "এলোমেলো", ready: "প্রস্তুত", placeFleet: "আপনার পাঁচটি জাহাজ বসিয়ে প্রস্তুত চাপুন। আপনার নৌবহর এই ফোনেই থাকে।", fleetWait: "অন্য নৌবহরের অপেক্ষায়", fleetLost: "আপনার নৌবহর আর এই ফোনে নেই; হার মেনে নতুন খেলা শুরু করুন।", fireAt: "সারি {row}, কলাম {col}-এ গুলি", shipsLeft: "{n}টি জাহাজ ভাসছে", allSunk: "পুরো নৌবহর ডুবে গেছে", dishonest: "একটি নৌবহর তার উত্তরের সঙ্গে মেলেনি", bothDishonest: "কোনো নৌবহরই তার উত্তরের সঙ্গে মেলেনি" },
  id: { name: "Perang Laut", yourSea: "Laut Anda", theirSea: "Laut mereka", cell: "Baris {row}, kolom {col}", water: "air", ship: "kapal", unknown: "belum ditembak", miss: "meleset", hit: "kena", sunk: "tenggelam", shuffle: "Acak", ready: "Siap", placeFleet: "Tempatkan lima kapal Anda, lalu ketuk Siap. Armada Anda tetap di ponsel ini.", fleetWait: "Menunggu armada lawan", fleetLost: "Armada Anda sudah tidak ada di ponsel ini; menyerahlah dan mulai pertandingan baru.", fireAt: "Tembak baris {row}, kolom {col}", shipsLeft: "{n} kapal mengapung", allSunk: "Seluruh armada tenggelam", dishonest: "Sebuah armada tidak cocok dengan jawabannya", bothDishonest: "Tidak ada armada yang cocok dengan jawabannya" },
  vi: { name: "Hải chiến", yourSea: "Biển của bạn", theirSea: "Biển của họ", cell: "Hàng {row}, cột {col}", water: "nước", ship: "tàu", unknown: "chưa bắn", miss: "trượt", hit: "trúng", sunk: "chìm", shuffle: "Xáo", ready: "Sẵn sàng", placeFleet: "Đặt năm con tàu rồi chạm Sẵn sàng. Hạm đội của bạn ở lại trên điện thoại này.", fleetWait: "Đang chờ hạm đội bên kia", fleetLost: "Hạm đội của bạn không còn trên điện thoại này; hãy đầu hàng và bắt đầu ván mới.", fireAt: "Bắn vào hàng {row}, cột {col}", shipsLeft: "{n} tàu còn nổi", allSunk: "Cả hạm đội đã bị đánh chìm", dishonest: "Một hạm đội không khớp với các câu trả lời", bothDishonest: "Không hạm đội nào khớp với các câu trả lời" },
  th: { name: "เรือรบ", yourSea: "ทะเลของคุณ", theirSea: "ทะเลของเขา", cell: "แถว {row} คอลัมน์ {col}", water: "น้ำ", ship: "เรือ", unknown: "ยังไม่ยิง", miss: "พลาด", hit: "โดน", sunk: "จม", shuffle: "สุ่ม", ready: "พร้อม", placeFleet: "วางเรือทั้งห้าลำแล้วแตะพร้อม กองเรือของคุณอยู่ในโทรศัพท์เครื่องนี้", fleetWait: "รอกองเรืออีกฝ่าย", fleetLost: "กองเรือของคุณไม่อยู่ในโทรศัพท์เครื่องนี้แล้ว ยอมแพ้แล้วเริ่มเกมใหม่", fireAt: "ยิงที่แถว {row} คอลัมน์ {col}", shipsLeft: "เรือลอยอยู่ {n} ลำ", allSunk: "กองเรือจมทั้งหมด", dishonest: "กองเรือหนึ่งไม่ตรงกับคำตอบของตน", bothDishonest: "ไม่มีกองเรือใดตรงกับคำตอบของตน" },
  ja: { name: "海戦", yourSea: "自分の海", theirSea: "相手の海", cell: "{row}行{col}列", water: "海", ship: "船", unknown: "未射撃", miss: "はずれ", hit: "命中", sunk: "撃沈", shuffle: "シャッフル", ready: "準備完了", placeFleet: "5隻の船を配置して「準備完了」をタップ。艦隊はこの端末にだけ残ります。", fleetWait: "相手の艦隊を待っています", fleetLost: "艦隊がこの端末にありません。降参して新しい対局を始めてください。", fireAt: "{row}行{col}列を撃つ", shipsLeft: "残り {n} 隻", allSunk: "艦隊が全滅", dishonest: "艦隊が回答と一致しませんでした", bothDishonest: "どちらの艦隊も回答と一致しませんでした" },
  ko: { name: "해전", yourSea: "내 바다", theirSea: "상대 바다", cell: "{row}행 {col}열", water: "바다", ship: "배", unknown: "아직 안 쏨", miss: "빗나감", hit: "명중", sunk: "격침", shuffle: "섞기", ready: "준비 완료", placeFleet: "배 다섯 척을 배치하고 준비 완료를 누르세요. 함대는 이 휴대폰에만 남습니다.", fleetWait: "상대 함대를 기다리는 중", fleetLost: "함대가 더 이상 이 휴대폰에 없어요. 기권하고 새 경기를 시작하세요.", fireAt: "{row}행 {col}열에 발사", shipsLeft: "{n}척 남음", allSunk: "함대가 모두 격침됨", dishonest: "한 함대가 자신의 답과 맞지 않았어요", bothDishonest: "어느 함대도 자신의 답과 맞지 않았어요" },
  "zh-CN": { name: "海战棋", yourSea: "你的海域", theirSea: "对方海域", cell: "第 {row} 行第 {col} 列", water: "海水", ship: "舰船", unknown: "未射击", miss: "未中", hit: "命中", sunk: "击沉", shuffle: "随机布阵", ready: "就绪", placeFleet: "布置五艘舰船，然后点“就绪”。你的舰队只留在这部手机上。", fleetWait: "等待对方舰队", fleetLost: "你的舰队已不在这部手机上；请认输并开始新的一局。", fireAt: "射击第 {row} 行第 {col} 列", shipsLeft: "尚有 {n} 艘", allSunk: "舰队全部被击沉", dishonest: "一方舰队与其回答不符", bothDishonest: "双方舰队都与其回答不符" },
  "zh-TW": { name: "海戰棋", yourSea: "你的海域", theirSea: "對方海域", cell: "第 {row} 列第 {col} 欄", water: "海水", ship: "艦船", unknown: "未射擊", miss: "未中", hit: "命中", sunk: "擊沉", shuffle: "隨機佈陣", ready: "就緒", placeFleet: "佈置五艘艦船，然後點「就緒」。你的艦隊只留在這支手機上。", fleetWait: "等待對方艦隊", fleetLost: "你的艦隊已不在這支手機上；請認輸並開始新的一局。", fireAt: "射擊第 {row} 列第 {col} 欄", shipsLeft: "尚有 {n} 艘", allSunk: "艦隊全部被擊沉", dishonest: "一方艦隊與其回答不符", bothDishonest: "雙方艦隊都與其回答不符" },
};
