// What Backgammon adds to the kit's texts, in the 21 languages of the app: its name (the plain
// name of the old game), the points, the bar, the trays, the dice, and how a round ends. English
// is the source. Data only (README, "Texts").

export const TEXTS = {
  en: { name: "Backgammon", point: "Point {n}", emptyPoint: "empty", checkers: "{n} checkers", yours: "yours", theirs: "theirs", bar: "Bar: {n} on it", off: "Borne off: {n}", dice: "Dice: {a} and {b}", rolling: "Rolling the dice…", pass: "No move: pass", moveTo: "Move to point {n}", bearOff: "Bear off", single: "All fifteen borne off", gammon: "Gammon: the other side bore off none", backgammonWin: "Backgammon: a checker still on the bar or in the winner's home", diceCheat: "The dice were not rolled as agreed", seedLost: "The roll was lost on this phone; resign and start a new match." },
  es: { name: "Backgammon", point: "Punto {n}", emptyPoint: "vacío", checkers: "{n} fichas", yours: "tuyas", theirs: "suyas", bar: "Barra: {n} encima", off: "Fuera: {n}", dice: "Dados: {a} y {b}", rolling: "Tirando los dados…", pass: "Sin jugada: pasar", moveTo: "Mover al punto {n}", bearOff: "Sacar", single: "Las quince fichas fuera", gammon: "Gammon: el otro lado no sacó ninguna", backgammonWin: "Backgammon: una ficha aún en la barra o en la casa del ganador", diceCheat: "Los dados no se tiraron como se acordó", seedLost: "La tirada se perdió en este teléfono; ríndete y empieza otra partida." },
  fr: { name: "Backgammon", point: "Flèche {n}", emptyPoint: "vide", checkers: "{n} pions", yours: "à vous", theirs: "à eux", bar: "Barre : {n} dessus", off: "Sortis : {n}", dice: "Dés : {a} et {b}", rolling: "Lancer des dés…", pass: "Aucun coup : passer", moveTo: "Aller à la flèche {n}", bearOff: "Sortir", single: "Les quinze pions sortis", gammon: "Gammon : l’autre camp n’en a sorti aucun", backgammonWin: "Backgammon : un pion encore sur la barre ou dans le jan du vainqueur", diceCheat: "Les dés n’ont pas été lancés comme convenu", seedLost: "Le lancer a été perdu sur ce téléphone ; abandonnez et commencez une autre partie." },
  de: { name: "Backgammon", point: "Feld {n}", emptyPoint: "leer", checkers: "{n} Steine", yours: "deine", theirs: "ihre", bar: "Bar: {n} darauf", off: "Abgetragen: {n}", dice: "Würfel: {a} und {b}", rolling: "Würfeln…", pass: "Kein Zug: passen", moveTo: "Auf Feld {n} ziehen", bearOff: "Abtragen", single: "Alle fünfzehn abgetragen", gammon: "Gammon: die andere Seite trug keinen ab", backgammonWin: "Backgammon: ein Stein noch auf der Bar oder im Heimfeld des Gewinners", diceCheat: "Die Würfel wurden nicht wie vereinbart geworfen", seedLost: "Der Wurf ging auf diesem Telefon verloren; gib auf und beginne eine neue Partie." },
  it: { name: "Backgammon", point: "Punta {n}", emptyPoint: "vuota", checkers: "{n} pedine", yours: "tue", theirs: "loro", bar: "Barra: {n} sopra", off: "Fuori: {n}", dice: "Dadi: {a} e {b}", rolling: "Lancio dei dadi…", pass: "Nessuna mossa: passa", moveTo: "Muovi alla punta {n}", bearOff: "Porta fuori", single: "Tutte e quindici le pedine fuori", gammon: "Gammon: l’altro lato non ne ha portata fuori nessuna", backgammonWin: "Backgammon: una pedina ancora sulla barra o nella casa del vincitore", diceCheat: "I dadi non sono stati lanciati come concordato", seedLost: "Il lancio è andato perso su questo telefono; arrenditi e inizia un’altra partita." },
  pt: { name: "Gamão", point: "Casa {n}", emptyPoint: "vazia", checkers: "{n} peças", yours: "tuas", theirs: "deles", bar: "Barra: {n} em cima", off: "Fora: {n}", dice: "Dados: {a} e {b}", rolling: "A lançar os dados…", pass: "Sem jogada: passar", moveTo: "Mover para a casa {n}", bearOff: "Retirar", single: "As quinze peças fora", gammon: "Gammon: o outro lado não retirou nenhuma", backgammonWin: "Gamão: uma peça ainda na barra ou na casa do vencedor", diceCheat: "Os dados não foram lançados como combinado", seedLost: "O lançamento perdeu-se neste telefone; desiste e começa outra partida." },
  ro: { name: "Table", point: "Câmpul {n}", emptyPoint: "gol", checkers: "{n} puluri", yours: "ale tale", theirs: "ale lor", bar: "Bară: {n} pe ea", off: "Scoase: {n}", dice: "Zaruri: {a} și {b}", rolling: "Se aruncă zarurile…", pass: "Nicio mutare: pas", moveTo: "Mută pe câmpul {n}", bearOff: "Scoate", single: "Toate cele cincisprezece scoase", gammon: "Marț: cealaltă parte nu a scos niciunul", backgammonWin: "Marț tehnic: un pul încă pe bară sau în casa câștigătorului", diceCheat: "Zarurile nu au fost aruncate cum s-a convenit", seedLost: "Aruncarea s-a pierdut pe acest telefon; predă-te și începe altă partidă." },
  pl: { name: "Tryktrak", point: "Pole {n}", emptyPoint: "puste", checkers: "{n} pionów", yours: "twoje", theirs: "ich", bar: "Bar: {n} na nim", off: "Zdjęte: {n}", dice: "Kości: {a} i {b}", rolling: "Rzut kośćmi…", pass: "Brak ruchu: pas", moveTo: "Przenieś na pole {n}", bearOff: "Zdejmij", single: "Wszystkie piętnaście zdjęte", gammon: "Gammon: druga strona nie zdjęła żadnego", backgammonWin: "Backgammon: pion wciąż na barze lub w domu zwycięzcy", diceCheat: "Kości nie zostały rzucone jak uzgodniono", seedLost: "Rzut przepadł na tym telefonie; poddaj się i zacznij nową partię." },
  ru: { name: "Нарды", point: "Пункт {n}", emptyPoint: "пусто", checkers: "Шашек: {n}", yours: "ваши", theirs: "соперника", bar: "Бар: {n} на нём", off: "Выведено: {n}", dice: "Кости: {a} и {b}", rolling: "Бросаем кости…", pass: "Хода нет: пропуск", moveTo: "Ход на пункт {n}", bearOff: "Вывести", single: "Все пятнадцать выведены", gammon: "Марс: соперник не вывел ни одной", backgammonWin: "Кокс: шашка ещё на баре или в доме победителя", diceCheat: "Кости брошены не так, как договорились", seedLost: "Бросок потерян на этом телефоне; сдайтесь и начните новую партию." },
  uk: { name: "Нарди", point: "Пункт {n}", emptyPoint: "порожньо", checkers: "Шашок: {n}", yours: "ваші", theirs: "суперника", bar: "Бар: {n} на ньому", off: "Виведено: {n}", dice: "Кості: {a} і {b}", rolling: "Кидаємо кості…", pass: "Ходу немає: пропуск", moveTo: "Хід на пункт {n}", bearOff: "Вивести", single: "Усі п’ятнадцять виведено", gammon: "Марс: суперник не вивів жодної", backgammonWin: "Кокс: шашка ще на барі або в домі переможця", diceCheat: "Кості кинуто не так, як домовилися", seedLost: "Кидок втрачено на цьому телефоні; здайтеся й почніть нову партію." },
  tr: { name: "Tavla", point: "Hane {n}", emptyPoint: "boş", checkers: "{n} pul", yours: "senin", theirs: "onların", bar: "Bar: {n} üstünde", off: "Toplanan: {n}", dice: "Zarlar: {a} ve {b}", rolling: "Zar atılıyor…", pass: "Hamle yok: pas", moveTo: "{n}. haneye taşı", bearOff: "Topla", single: "On beş pulun hepsi toplandı", gammon: "Mars: karşı taraf hiç toplayamadı", backgammonWin: "Çifte mars: bir pul hâlâ barda ya da kazananın evinde", diceCheat: "Zarlar anlaşıldığı gibi atılmadı", seedLost: "Zar atışı bu telefonda kayboldu; pes et ve yeni bir oyun başlat." },
  ar: { name: "طاولة", point: "الخانة {n}", emptyPoint: "فارغة", checkers: "{n} قطع", yours: "لك", theirs: "لهم", bar: "الحاجز: {n} عليه", off: "خرجت: {n}", dice: "الزهر: {a} و{b}", rolling: "جارٍ رمي الزهر…", pass: "لا حركة: تمرير", moveTo: "الانتقال إلى الخانة {n}", bearOff: "إخراج", single: "خرجت القطع الخمس عشرة كلها", gammon: "مارس: لم يُخرج الطرف الآخر أي قطعة", backgammonWin: "مارس مضاعف: قطعة ما زالت على الحاجز أو في بيت الفائز", diceCheat: "لم يُرمَ الزهر كما اتُّفق", seedLost: "ضاعت الرمية على هذا الهاتف؛ استسلم وابدأ مباراة جديدة." },
  hi: { name: "बैकगैमन", point: "बिंदु {n}", emptyPoint: "खाली", checkers: "{n} गोटियाँ", yours: "आपकी", theirs: "उनकी", bar: "बार: {n} उस पर", off: "बाहर: {n}", dice: "पासे: {a} और {b}", rolling: "पासे फेंके जा रहे हैं…", pass: "कोई चाल नहीं: पास", moveTo: "बिंदु {n} पर ले जाएँ", bearOff: "बाहर निकालें", single: "सभी पंद्रह गोटियाँ बाहर", gammon: "गैमन: दूसरे पक्ष ने एक भी नहीं निकाली", backgammonWin: "बैकगैमन: एक गोटी अभी भी बार पर या विजेता के घर में", diceCheat: "पासे तय तरीके से नहीं फेंके गए", seedLost: "इस फ़ोन पर फेंक खो गई; हार मानें और नई बाज़ी शुरू करें।" },
  bn: { name: "ব্যাকগ্যামন", point: "ঘর {n}", emptyPoint: "খালি", checkers: "{n}টি গুটি", yours: "আপনার", theirs: "ওদের", bar: "বার: {n}টি এর উপর", off: "বের হয়েছে: {n}", dice: "ছক্কা: {a} ও {b}", rolling: "ছক্কা গড়ানো হচ্ছে…", pass: "চাল নেই: পাস", moveTo: "ঘর {n}-এ সরান", bearOff: "বের করুন", single: "পনেরোটি গুটিই বের হয়েছে", gammon: "গ্যামন: অন্য পক্ষ একটিও বের করেনি", backgammonWin: "ব্যাকগ্যামন: একটি গুটি এখনও বারে বা বিজয়ীর ঘরে", diceCheat: "ছক্কা চুক্তিমতো গড়ানো হয়নি", seedLost: "এই ফোনে চালটি হারিয়ে গেছে; হার মেনে নতুন খেলা শুরু করুন।" },
  id: { name: "Backgammon", point: "Titik {n}", emptyPoint: "kosong", checkers: "{n} bidak", yours: "milik Anda", theirs: "milik mereka", bar: "Bar: {n} di atasnya", off: "Keluar: {n}", dice: "Dadu: {a} dan {b}", rolling: "Melempar dadu…", pass: "Tidak ada langkah: lewat", moveTo: "Pindah ke titik {n}", bearOff: "Keluarkan", single: "Kelima belas bidak keluar", gammon: "Gammon: pihak lain tidak mengeluarkan satu pun", backgammonWin: "Backgammon: sebuah bidak masih di bar atau di rumah pemenang", diceCheat: "Dadu tidak dilempar seperti yang disepakati", seedLost: "Lemparan hilang di ponsel ini; menyerahlah dan mulai pertandingan baru." },
  vi: { name: "Cờ tào cáo", point: "Điểm {n}", emptyPoint: "trống", checkers: "{n} quân", yours: "của bạn", theirs: "của họ", bar: "Thanh chắn: {n} quân", off: "Đã ra: {n}", dice: "Xúc xắc: {a} và {b}", rolling: "Đang gieo xúc xắc…", pass: "Không có nước đi: bỏ lượt", moveTo: "Đi đến điểm {n}", bearOff: "Đưa ra", single: "Cả mười lăm quân đã ra", gammon: "Gammon: bên kia chưa đưa ra quân nào", backgammonWin: "Backgammon: một quân vẫn trên thanh chắn hoặc trong nhà bên thắng", diceCheat: "Xúc xắc không được gieo như đã thỏa thuận", seedLost: "Lượt gieo bị mất trên điện thoại này; hãy đầu hàng và bắt đầu ván mới." },
  th: { name: "แบ็กแกมมอน", point: "ช่อง {n}", emptyPoint: "ว่าง", checkers: "{n} ตัว", yours: "ของคุณ", theirs: "ของเขา", bar: "บาร์: {n} ตัวอยู่บนนั้น", off: "ออกแล้ว: {n}", dice: "ลูกเต๋า: {a} และ {b}", rolling: "กำลังทอยลูกเต๋า…", pass: "เดินไม่ได้: ผ่าน", moveTo: "ย้ายไปช่อง {n}", bearOff: "เอาออก", single: "ออกครบทั้งสิบห้าตัว", gammon: "แกมมอน: อีกฝ่ายยังไม่ได้เอาออกเลย", backgammonWin: "แบ็กแกมมอน: ยังมีตัวหมากอยู่บนบาร์หรือในบ้านของผู้ชนะ", diceCheat: "ลูกเต๋าไม่ได้ถูกทอยตามที่ตกลง", seedLost: "การทอยหายไปจากโทรศัพท์เครื่องนี้ ยอมแพ้แล้วเริ่มเกมใหม่" },
  ja: { name: "バックギャモン", point: "ポイント {n}", emptyPoint: "空き", checkers: "駒 {n} 個", yours: "自分", theirs: "相手", bar: "バー：{n} 個", off: "上がり：{n}", dice: "ダイス：{a} と {b}", rolling: "ダイスを振っています…", pass: "動かせる駒なし：パス", moveTo: "ポイント {n} へ", bearOff: "上げる", single: "15個すべて上がり", gammon: "ギャモン：相手は1個も上がれず", backgammonWin: "バックギャモン：相手の駒がバーか勝者のインナーに残った", diceCheat: "ダイスが取り決めどおりに振られていません", seedLost: "ロールがこの端末から失われました。降参して新しい対局を始めてください。" },
  ko: { name: "백개먼", point: "포인트 {n}", emptyPoint: "비어 있음", checkers: "말 {n}개", yours: "내 것", theirs: "상대 것", bar: "바: {n}개", off: "빼낸 말: {n}", dice: "주사위: {a}와 {b}", rolling: "주사위를 굴리는 중…", pass: "둘 수 없음: 패스", moveTo: "포인트 {n}(으)로 이동", bearOff: "빼내기", single: "말 열다섯 개를 모두 빼냄", gammon: "개먼: 상대는 하나도 빼내지 못함", backgammonWin: "백개먼: 상대 말이 아직 바나 승자의 홈에 있음", diceCheat: "약속대로 주사위를 굴리지 않았어요", seedLost: "이 휴대폰에서 굴림이 사라졌어요. 기권하고 새 경기를 시작하세요." },
  "zh-CN": { name: "双陆棋", point: "第 {n} 点", emptyPoint: "空", checkers: "{n} 枚棋子", yours: "你的", theirs: "对方的", bar: "中栏：{n} 枚", off: "已出：{n}", dice: "骰子：{a} 和 {b}", rolling: "掷骰中…", pass: "无子可动：跳过", moveTo: "移到第 {n} 点", bearOff: "出子", single: "十五枚棋子全部出完", gammon: "全胜：对方一枚未出", backgammonWin: "大全胜：对方还有棋子在中栏或胜方内区", diceCheat: "骰子未按约定投掷", seedLost: "本次投掷已不在这部手机上；请认输并开始新的一局。" },
  "zh-TW": { name: "雙陸棋", point: "第 {n} 點", emptyPoint: "空", checkers: "{n} 枚棋子", yours: "你的", theirs: "對方的", bar: "中欄：{n} 枚", off: "已出：{n}", dice: "骰子：{a} 和 {b}", rolling: "擲骰中…", pass: "無子可動：跳過", moveTo: "移到第 {n} 點", bearOff: "出子", single: "十五枚棋子全部出完", gammon: "全勝：對方一枚未出", backgammonWin: "大全勝：對方還有棋子在中欄或勝方內區", diceCheat: "骰子未按約定投擲", seedLost: "本次投擲已不在這支手機上；請認輸並開始新的一局。" },
};
